cache: npm
before_install:
  - sed 's/MAPBOX_TOKEN/dummy_token/' settings.json.example > settings.json
  - cp firebase-config.json.example firebase-config.json
install:
  - npm install
language: node_js
node_js:
  - '10'
  - '8'
script:
  - npm run lint
  - npm run release
