git:
  depth: false
  quiet: true
cache: npm
before_install:
  - echo '{}' > disabled.json
  - sed 's/MAPBOX_TOKEN/dummy_token/' settings.json.example > settings.json
  - cp firebase-config.json.example firebase-config.json
  - echo "${SETTINGS_DEV}" | base64 -d > settings.json.dev
  - echo "${SETTINGS_PROD}" | base64 -d > settings.json.prod
  - echo "${FIREBASE_DEV}" | base64 -d > firebase-config.json.dev
  - echo "${FIREBASE_PROD}" | base64 -d > firebase-config.json.prod
install:
  - npm ci
language: node_js
node_js:
  - '12'
script:
  - npm run lint
  - npm run stylelint
  - npm run release
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "master" ]];then
      bash docker.fast.sh buildpush prod prod;
    else
      bash docker.fast.sh buildpush dev dev;
    fi'
