cache: npm
before_install:
  - echo '{}' > disabled.json
  - sed 's/MAPBOX_TOKEN/dummy_token/' settings.json.example > settings.json
  - cp firebase-config.json.example firebase-config.json
install:
  - npm ci
language: node_js
node_js:
  - '12'
script:
  - npm run lint
  - npm run stylelint
  - npm run release
