FROM nginx:stable AS release
LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

ENV HTML_FOLDER=/usr/share/nginx/html
COPY dist_release ${HTML_FOLDER}
COPY static ${HTML_FOLDER}
COPY 99-env-configs.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/99-env-configs.sh
COPY nginx.conf.template /etc/nginx/templates/default.conf.template
