# docker-compose.yml (tag: v4)
version: '2'
services:
  web:
    build: .
    links:
    - "db:database"
    ports:
    - "3000:3000"
    volumes:
    - .:/chronist/:rw
    - /chronist/node_modules
    environment:
    - NODE_ENV=dev
  db:
    image: "postgres:latest"
    ports:
    - "15432:5432"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d