version: "3.7"
services:
  frontend:
    build:
      context: .
      target: dev
    volumes:
      - '.:/chronmaps'
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - EXT=true
