# docker-compose.yml (tag: v4)
version: '2'
services:
  web:
    build: .
    links:
    - "db:database"
    ports:
    - "3000:3000"
    volumes:
    - .:/chronist/:rw
    - /chronist/node_modules
    command: npm run dev
  db:
    image: "postgres:alpine"
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=chronist
    ports:
    - "15432:5432"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d