--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.3
-- Dumped by pg_dump version 9.6.3

-- Started on 2017-09-08 11:20:08 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 198 (class 1259 OID 16819)
-- Name: inventions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE inventions (
    id integer NOT NULL,
    name_eng text,
    name_rus text,
    description text,
    invent_date bigint,
    inventor text,
    invent_place bigint,
    link text
);


ALTER TABLE inventions OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 16817)
-- Name: inventions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE inventions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE inventions_id_seq OWNER TO postgres;

--
-- TOC entry 2197 (class 0 OID 0)
-- Dependencies: 197
-- Name: inventions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE inventions_id_seq OWNED BY inventions.id;


--
-- TOC entry 2071 (class 2604 OID 16822)
-- Name: inventions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventions ALTER COLUMN id SET DEFAULT nextval('inventions_id_seq'::regclass);


--
-- TOC entry 2192 (class 0 OID 16819)
-- Dependencies: 198
-- Data for Name: inventions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO inventions VALUES (1, 'Swim fins', 'Ласты', 'Приспособление для плавания в форме плавника или весла', 1717, '{2}', 267, 'https://en.wikipedia.org/wiki/Swimfin');
INSERT INTO inventions VALUES (2, 'Octant', 'Октант', 'Угломерный отражательный инструмент, ныне вышедший из употребления', 1730, '{3}', 0, 'https://en.wikipedia.org/wiki/Combine_harvester');
INSERT INTO inventions VALUES (3, 'Flexible urinary catheter', 'Гибкий мочевой катетер', 'Латексная, полиуретановая или силиконовая трубка вставленная в мочевой пузырь пациента в медицинских целях', 1752, '{2}', 269, 'https://en.wikipedia.org/wiki/Urinary_catheterization');
INSERT INTO inventions VALUES (4, 'Bifocals', 'Бифокальная линза', 'Линза с двумя оптическими зонами. Обычно имеет большой сегмент для дали и сегмент для чтения', 1784, '{2}', 269, 'https://en.wikipedia.org/wiki/Bifocals');
INSERT INTO inventions VALUES (5, 'Fire hydrant', 'Пожарный гидрант', 'Устройство для отбора воды из водопроводной сети для тушения пожара', 1792, '{4}', 269, 'https://en.wikipedia.org/wiki/Fire_hydrant');
INSERT INTO inventions VALUES (6, 'Vapor-compression refrigeration', 'Компрессионная холодильная машина', 'Устройство, служащее для отвода теплоты от охлаждаемого тела', 1805, '{5}', 269, 'https://en.wikipedia.org/wiki/Vapor-compression_refrigeration');
INSERT INTO inventions VALUES (7, 'Circular saw', 'Цикрулярная пила', 'Режущий инструмент в виде плоского металлического диска, на внешней кромке которого расположены зубья', 1813, '{6}', 156, 'https://en.wikipedia.org/wiki/Circular_saw');
INSERT INTO inventions VALUES (8, 'Electric doorbell', 'Электрический звонок', 'Электрический звонок активируемый выносной кнопкой', 1831, '{7}', 156, 'https://en.wikipedia.org/wiki/Doorbell');
INSERT INTO inventions VALUES (9, 'Combine harvester', 'Зерноуборочный комбайн', 'Машина, которая одновременно срезала хлеб, обмолачивала его и очищала зерно от шелухи', 1834, '{8}', 289, 'https://en.wikipedia.org/wiki/Combine_harvester');
INSERT INTO inventions VALUES (10, 'Relay', 'Реле', 'Электрическое устройство, предназначенное для замыкания или размыкания электрической цепи', 1835, '{7}', 291, 'https://en.wikipedia.org/wiki/Relay');
INSERT INTO inventions VALUES (11, 'Lobster Trap', 'Ловушка для лобстеров', 'Ловушка с конусовидным входом направленным во внутрь', 1808, '{10}', 294, 'https://en.wikipedia.org/wiki/Lobster_trap');
INSERT INTO inventions VALUES (12, 'Baseball', 'Бейсбол', 'Командная спортивная игра с бейсбольным мячом и битой', 1845, '{9}', 285, 'https://en.wikipedia.org/wiki/Baseball');
INSERT INTO inventions VALUES (13, 'Printing telegraph', 'Буквопечатающий телеграфный аппарат', 'Скорость передачи была около 40 слов в минуту, или до 2000 слов в час', 1846, '{11}', 285, 'https://en.wikipedia.org/wiki/Printing_telegraph');
INSERT INTO inventions VALUES (14, 'Morse code', 'Азбука Морзе', 'Способ знакового кодирования последовательностью сигналов: длинных («тире») и коротких («точек»)', 1836, '{13,12}', 284, 'https://en.wikipedia.org/wiki/Morse_code');
INSERT INTO inventions VALUES (15, 'Inhalational anaesthetic', 'Ингаляционный анестетик', 'Анастезия которая может быть доставлено путём ингаляции', 1842, '{14}', 269, 'https://en.wikipedia.org/wiki/Inhalational_anaesthetic');
INSERT INTO inventions VALUES (16, 'Gas mask', 'Противогаз', 'Маска для защиты от вдыхания загрязняющих веществ в воздухе и токсичных газов', 1847, '{15}', 0, 'https://en.wikipedia.org/wiki/Gas_mask');
INSERT INTO inventions VALUES (17, 'Safety pin', 'Английская булавка', 'Разновидность булавки, в которой остриё иглы накрывается крышкой для защиты от случайного укола', 1849, '{16}', 285, 'https://en.wikipedia.org/wiki/Safety_pin');
INSERT INTO inventions VALUES (18, 'Inverted microscope', 'Инвертированный микроскоп', 'Оптический прибор с «перевернутой» конструкцией, которая позволяет вести исследование объекта с его нижней стороны', 1850, '{17}', 265, 'https://en.wikipedia.org/wiki/Inverted_microscope');
INSERT INTO inventions VALUES (19, 'Potato chips', 'Картофельные чипсы', 'Закуска, представляющая собой зажаренные тонкие ломтики картофеля', 1853, '{18}', 301, 'https://en.wikipedia.org/wiki/Potato_chip');
INSERT INTO inventions VALUES (20, 'Spring Clothespin', 'Прищепка с пружинным зажимом', 'Специальный вид зажима, обычно использующийся для крепления предметов в верёвке', 1853, '{19}', 302, 'https://en.wikipedia.org/wiki/Clothespin');
INSERT INTO inventions VALUES (21, 'Calliope', 'Каллиопа', 'Паровой орган, использующий локомотивные или пароходные гудки', 1855, '{20}', 303, 'https://en.wikipedia.org/wiki/Calliope_(music)');
INSERT INTO inventions VALUES (22, 'Condensed milk', 'Сгущенное молоко', 'Концентрированное молоко, обычно с сахаров', 1856, '{21}', 0, 'https://en.wikipedia.org/wiki/Condensed_milk');
INSERT INTO inventions VALUES (23, 'Equatorial sextant', 'Секстант', 'Навигационные измерительный инструмент', 1856, '{22}', 270, 'https://en.wikipedia.org/wiki/Equatorial_sextant');
INSERT INTO inventions VALUES (24, 'Toilet paper', 'Туалетная бумага', 'Бумажное изделие, используемое в санитарно-гигиенических целях', 1857, '{23}', 285, 'https://en.wikipedia.org/wiki/Toilet_paper');
INSERT INTO inventions VALUES (25, 'Pencil eraser', 'Ластик, закрепленный на карандаше', 'Стирательная резинка, закрепленная на конце карандаша, противоположном заточенному', 1858, '{24}', 269, 'https://en.wikipedia.org/wiki/Pencil#Eraser_attached');
INSERT INTO inventions VALUES (26, 'Escalator', 'Эскалатор', 'Подъёмно-транспортная машина для перемещения людей с одного уровня на другой', 1859, '{25}', 307, 'https://en.wikipedia.org/wiki/Escalator');
INSERT INTO inventions VALUES (27, 'Vacuum cleaner', 'Пылесос', 'Машина для уборки пыли за счет всасывания потоком воздуха', 1860, '{26}', 308, 'https://en.wikipedia.org/wiki/Vacuum_cleaner');
INSERT INTO inventions VALUES (223, 'Standard time', 'Поясное время', 'Деление мира на часовые пояса', 1878, '{241}', 282, 'https://en.wikipedia.org/wiki/Standard_time');
INSERT INTO inventions VALUES (28, 'Kinematoscope', 'Кинематоскоп', 'Устройство для показа коротких анимаций посредством вращения картинок', 1861, '{27}', 269, 'https://en.wikipedia.org/wiki/Kinematoscope');
INSERT INTO inventions VALUES (29, 'Postcard', 'Почтовая карточка', 'Вид почтового отправления с письменным сообщением на бланке из плотной бумаги', 1861, '{24,28}', 269, 'https://en.wikipedia.org/wiki/Postcard');
INSERT INTO inventions VALUES (30, 'Machine gun (hand-cranked)', 'Пулемёт', 'Стрелковое автоматическое оружие', 1861, '{29}', 0, 'https://en.wikipedia.org/wiki/Gatling_gun');
INSERT INTO inventions VALUES (31, 'Cowboy hat', 'Ковбойская шляпа', 'Шляпа, с высокой округлой тульёй, вогнутой сверху, и с широкими подогнутыми вверх по бокам полями', 1865, '{30}', 0, 'https://en.wikipedia.org/wiki/Cowboy_hat');
INSERT INTO inventions VALUES (32, 'Rotary printing press', 'Ротационная печатная машина', 'Устройство для типографской печати, имеющее цилиндрическую форму рабочего органа', 1865, '{31}', 312, 'https://en.wikipedia.org/wiki/Rotary_printing_press');
INSERT INTO inventions VALUES (33, 'Barbed wire', 'Колючая проволока', 'Проволока с расположенными на ней острыми шипами', 1867, '{32}', 313, 'https://en.wikipedia.org/wiki/Barbed_wire');
INSERT INTO inventions VALUES (34, 'Refrigerator car', 'Изотермический вагон', 'Крытый грузовой вагон для перевозки скоропортящихся грузов', 1867, '{33}', 270, 'https://en.wikipedia.org/wiki/Refrigerator_car');
INSERT INTO inventions VALUES (35, 'Paper bag', 'Бумажный пакет', 'Пакет из бумаги', 1868, '{34}', 14, 'https://en.wikipedia.org/wiki/Paper_bag');
INSERT INTO inventions VALUES (36, 'Pipe wrench', 'Разводной ключ', 'Инструмент, используемый для вращения гаек, болтов и других деталей', 1869, '{35}', 316, 'https://en.wikipedia.org/wiki/Pipe_wrench');
INSERT INTO inventions VALUES (37, 'Can opener (rotary)', 'Консервный нож (с колесиком)', 'Приспособление для открытия жестяных консервных банок', 1870, '{36}', 318, 'https://en.wikipedia.org/wiki/Can_opener#Rotating_wheel_openers');
INSERT INTO inventions VALUES (38, 'Railway air brake', 'Воздушный тормоз Вестингауза', 'Система привода тормозов в железнодорожном транспорте, использующих для работы сжатый воздух', 1872, '{37}', 312, 'https://en.wikipedia.org/wiki/Railway_air_brake');
INSERT INTO inventions VALUES (39, 'Earmuffs', 'Защитные наушники', 'Устройства для покрытия ушей и защиты от внешних воздействий', 1873, '{38}', 320, 'https://en.wikipedia.org/wiki/Earmuffs');
INSERT INTO inventions VALUES (40, 'Jeans', 'Джинсы', 'Брюки из плотной хлопчатобумажной ткани, с проклёпанными стыками швов на карманах', 1873, '{39,40}', 276, 'https://en.wikipedia.org/wiki/Jeans');
INSERT INTO inventions VALUES (41, 'Knuckle coupler', 'Автосцепка Джаннея', 'Автоматическое сцепное устройство, применяемое на железнодорожном транспорте', 1873, '{41}', 68, 'https://en.wikipedia.org/wiki/Janney_coupler');
INSERT INTO inventions VALUES (42, 'QWERTY', 'QWERTY', 'Наиболее популярная в настоящее время латинская раскладка клавиатуры, используемая для английского языка', 1874, '{42}', 235, 'https://en.wikipedia.org/wiki/QWERTY');
INSERT INTO inventions VALUES (43, 'Dental drill (electric)', 'Бормашина', 'Ротационный инструмент, развивающий высокую частоту вращения шпинделя при небольшом крутящем моменте', 1875, '{43}', 323, 'https://en.wikipedia.org/wiki/Dental_drill');
INSERT INTO inventions VALUES (44, 'Synthesizer', 'Синтезатор', 'Электронный музыкальный инструмент, создающий звук при помощи одного или нескольких генераторов звуковых волн', 1876, '{44}', 0, 'https://en.wikipedia.org/wiki/Synthesizer');
INSERT INTO inventions VALUES (45, 'Tattoo machine', 'Индукционная машинка (для татуировки)', 'Современный инструмент для нанесения татуировки, в основе работы лежит электрический колебательный контур', 1876, '{45}', 69, 'https://en.wikipedia.org/wiki/Tattoo_machine');
INSERT INTO inventions VALUES (46, 'Phonograph', 'Фонограф', 'Первый прибор для записи и воспроизведения звука', 1877, '{45}', 328, 'https://en.wikipedia.org/wiki/Phonograph');
INSERT INTO inventions VALUES (47, 'District heating', 'Теплоснабжение', 'Система обеспечения теплом зданий и сооружений, предназначенная для обеспечения теплового комфорта', 1877, '{46}', 330, 'https://en.wikipedia.org/wiki/District_heating');
INSERT INTO inventions VALUES (48, 'Carbon microphone', 'Угольный микрофон', 'Один из первых типов микрофонов', 1878, '{45}', 328, 'https://en.wikipedia.org/wiki/Carbon_microphone');
INSERT INTO inventions VALUES (49, 'Free jet water turbine', 'Ковшовая турбина (турбина Пелтона)', 'Активная гидравлическая турбина, используемая при очень больших напорах', 1878, '{47}', 332, 'https://en.wikipedia.org/wiki/Pelton_wheel');
INSERT INTO inventions VALUES (50, 'Mechanical production of Photographic plate', 'Фотопластинка', 'Фотоматериал на стеклянной подложке', 1879, '{48}', 166, 'https://en.wikipedia.org/wiki/Photographic_plate');
INSERT INTO inventions VALUES (51, 'Cash register', 'Контрольно-кассовая машина', 'Машина, предназначеная для механизации кассовых операций', 1879, '{49}', 114, 'https://en.wikipedia.org/wiki/Cash_register');
INSERT INTO inventions VALUES (52, 'Electric chair', 'Электрический стул', 'Приспособление, с помощью которого в некоторых штатах США приводятся в исполнение смертные приговоры', 1881, '{50}', 236, 'https://en.wikipedia.org/wiki/Electric_chair');
INSERT INTO inventions VALUES (53, 'Metal detector', 'Металлоискатель', 'Электронный прибор, позволяющий обнаруживать металлические предметы за счёт их проводимости', 1881, '{51}', 0, 'https://en.wikipedia.org/wiki/Metal_detector');
INSERT INTO inventions VALUES (54, 'Fan (electric)', 'Вентилятор', 'Устройство для перемещения газа', 1882, '{52}', 285, 'https://en.wikipedia.org/wiki/Mechanical_fan');
INSERT INTO inventions VALUES (55, 'Solar cell', 'Фотоэлемент (солнечная батарея)', 'Электронный прибор, который преобразует энергию фотонов в электрическую энергию', 1883, '{53}', 285, 'https://en.wikipedia.org/wiki/Solar_cell');
INSERT INTO inventions VALUES (56, 'Machine gun (Maxim gun)', 'Пулемёт Максима', 'Станковый пулемёт, разработанный британским оружейником американского происхождения Х. С. Максимом', 1884, '{54}', 0, 'https://en.wikipedia.org/wiki/Maxim_gun');
INSERT INTO inventions VALUES (57, 'Skyscraper', 'Небоскреб', 'Очень высокое здание с несущим стальным или железобетонным каркасом', 1884, '{55}', 279, 'https://en.wikipedia.org/wiki/Skyscraper');
INSERT INTO inventions VALUES (58, 'Popcorn machine', 'Машина для производства попкорна', 'Машина для приготовления попкорна', 1885, '{56}', 279, 'https://en.wikipedia.org/wiki/Popcorn_maker');
INSERT INTO inventions VALUES (59, 'Photographic film', 'Фотоплёнка', 'Фотоматериал на гибкой полимерной подложке, предназначенный для различных видов фотографии', 1885, '{48}', 166, 'https://en.wikipedia.org/wiki/Photographic_film');
INSERT INTO inventions VALUES (60, 'Gramophone record', 'Грампластинка', 'Аналоговый носитель звуковой информации', 1887, '{57}', 284, 'https://en.wikipedia.org/wiki/Gramophone_record');
INSERT INTO inventions VALUES (61, 'Slot machine', 'Слот-машина (однорукий бандит)', 'Игровой автомат, дающий шанс выиграть сумму, во много раз бо?льшую чем размер ставки', 1887, '{58}', 276, 'https://en.wikipedia.org/wiki/Slot_machine');
INSERT INTO inventions VALUES (62, 'Trolley pole', 'Штанга (токоприемник)', 'Тип токоприёмника, представляющий собой в рабочем состоянии направленную вверх штангу', 1888, '{59}', 194, 'https://en.wikipedia.org/wiki/Trolley_pole');
INSERT INTO inventions VALUES (63, 'Drinking straw', 'Соломинка (для напитков)', 'Приспособление в виде трубочки для втягивания напитков из бокала в рот', 1888, '{60}', 284, 'https://en.wikipedia.org/wiki/Drinking_straw');
INSERT INTO inventions VALUES (64, 'Stepping switch', 'Шаговый искатель', 'Электромеханический коммутационный аппарат, применяемый в системах коммутации и автоматизации', 1888, '{61}', 177, 'https://en.wikipedia.org/wiki/Stepping_switch');
INSERT INTO inventions VALUES (65, 'Touch typing', 'Слепой метод печати', 'Методика набора текста «вслепую», то есть не глядя на клавиши, используя все пальцы рук', 1888, '{62}', 72, 'https://en.wikipedia.org/wiki/Touch_typing');
INSERT INTO inventions VALUES (66, 'Stop sign', 'Дорожный знак "Стоп"', 'Дорожный знак приоритета, предписывающий водителям совершить обязательную кратковременную остановку перед ним', 1890, '{63}', 285, 'https://en.wikipedia.org/wiki/Stop_sign');
INSERT INTO inventions VALUES (67, 'Smoke detector', 'Пожарный извещатель', 'Техническое средство, предназначенное для формирования сигнала о пожаре', 1890, '{64}', 0, 'https://en.wikipedia.org/wiki/Smoke_detector');
INSERT INTO inventions VALUES (68, 'Ferris wheel', 'Колесо обозрения', 'Аттракцион в виде большого вертикально установленного колеса, к ободу которого прикреплены кабинки для пассажиров', 1891, '{65}', 279, 'https://en.wikipedia.org/wiki/Ferris_wheel');
INSERT INTO inventions VALUES (69, 'Tesla coil', 'Трансформатор Теслы', 'Устройство, изобретённое Николой Теслой и носящее его имя', 1891, '{66}', 285, 'https://en.wikipedia.org/wiki/Tesla_coil');
INSERT INTO inventions VALUES (70, 'Rotary dial', 'Номеронабиратель', 'Составная часть телефонного аппарата', 1891, '{61}', 177, 'https://en.wikipedia.org/wiki/Rotary_dial');
INSERT INTO inventions VALUES (71, 'Bottle cap', 'Бутылочная пробка', 'Кусок какого-либо материала определённой формы, используемый для закупоривания бутылок', 1892, '{67}', 196, 'https://en.wikipedia.org/wiki/Bottle_cap');
INSERT INTO inventions VALUES (72, 'Bicycle seat', 'Велосипедное сиденье', 'Часть велосипеда, принимающая на себя бо?льшую часть веса велосипедиста', 1892, '{68}', 341, 'https://en.wikipedia.org/wiki/Bicycle_seat');
INSERT INTO inventions VALUES (73, 'Zipper', 'Застежка-молния', 'Вид застёжек, предназначенных для быстрого соединения деталей одежды', 1893, '{69}', 0, 'https://en.wikipedia.org/wiki/Zipper');
INSERT INTO inventions VALUES (74, 'Medical glove', 'Медицинские перчатки', 'Одноразовые перчатки, являющиеся медицинской принадлежностью для обеспечения безопасности персонала и пациента', 1894, '{70}', 196, 'https://en.wikipedia.org/wiki/Medical_glove');
INSERT INTO inventions VALUES (75, 'Volleyball', 'Волейбол', 'Вид спорта, командная спортивная игра', 1895, '{71}', 343, 'https://en.wikipedia.org/wiki/Volleyball');
INSERT INTO inventions VALUES (76, 'Cotton candy', 'Сахарная вата', 'Кулинарный продукт, сладость, напоминающая по виду вату', 1897, '{72}', 232, 'https://en.wikipedia.org/wiki/Cotton_candy');
INSERT INTO inventions VALUES (77, 'Remote control', 'Пульт дистанционного управления', 'Электронное устройство для удалённого (дистанционного) управления устройством на расстоянии', 1898, '{66}', 285, 'https://en.wikipedia.org/wiki/Remote_control');
INSERT INTO inventions VALUES (78, 'Semi-automatic shotgun', 'Полуавтоматическое ружье', 'Автоматическое оружие, спусковой механизм которого позволяет вести только одиночную стрельбу', 1898, '{73}', 344, 'https://en.wikipedia.org/wiki/Semi-automatic_shotgun');
INSERT INTO inventions VALUES (79, 'Nickel–zinc battery', 'Никель-цинковый аккумулятор', NULL, 1900, '{45}', 328, 'https://en.wikipedia.org/wiki/Nickel–zinc_battery');
INSERT INTO inventions VALUES (80, 'Fly swatter', 'Мухобойка', 'Инструмент для отпугивания или прихлопывания мух', 1900, '{74}', 0, 'https://en.wikipedia.org/wiki/Fly-killing_device');
INSERT INTO inventions VALUES (81, 'Mercury-vapor lamp', 'Ртутная газоразрядная лампа', 'Источник света, в котором для генерации оптического излучения используется газовый разряд в парах ртути', 1901, '{75}', 285, 'https://en.wikipedia.org/wiki/Mercury-vapor_lamp');
INSERT INTO inventions VALUES (82, 'Assembly line', 'Конвейер', 'Машина непрерывного транспорта, предназначенная для перемещения сыпучих, кусковых или штучных грузов', 1901, '{76}', 119, 'https://en.wikipedia.org/wiki/Assembly_line');
INSERT INTO inventions VALUES (83, 'Safety razor', 'Бритвенный станок', 'Приспособление, которое держит лезвие бритвы во время бритья', 1901, '{77}', 0, 'https://en.wikipedia.org/wiki/Safety_razor');
INSERT INTO inventions VALUES (84, 'Radio direction finder', 'Радиокомпас', 'Бортовой радиопеленгатор, предназначенный для навигации по сигналам наземных радиостанций ', 1901, '{78}', 267, 'https://en.wikipedia.org/wiki/Radio_direction_finder');
INSERT INTO inventions VALUES (85, 'Hearing aid', 'Слуховой аппарат', 'Электронный звукоусиливающий прибор, применяющийся при различных формах стойких нарушений слуха', 1902, '{79}', 285, 'https://en.wikipedia.org/wiki/Hearing_aid');
INSERT INTO inventions VALUES (86, 'Teddy bear', 'Плюшевый мишка', 'Игрушечный медведь из мягкого материал', 1902, '{80}', 285, 'https://en.wikipedia.org/wiki/Teddy_bear');
INSERT INTO inventions VALUES (87, 'Periscope', 'Перископ', 'Оптический прибор для наблюдения из укрытия', 1902, '{81}', 349, 'https://en.wikipedia.org/wiki/Periscope');
INSERT INTO inventions VALUES (88, 'Air conditioning', 'Кондиционирование воздуха', 'Автоматическое поддержание в закрытых помещениях всех или отдельных параметров воздуха', 1902, '{82}', 236, 'https://en.wikipedia.org/wiki/Air_conditioning');
INSERT INTO inventions VALUES (89, 'Airplane', 'Самолет', 'Воздушное судно, предназначенное для полётов в атмосфере с помощью силовой установки', 1903, '{83,84}', 352, 'https://en.wikipedia.org/wiki/Airplane');
INSERT INTO inventions VALUES (90, 'Windshield wipers', 'Стеклоочиститель ("дворники")', 'Устройство, используемое для удаления капель дождя (влаги) и грязи с ветрового стекла автомобиля', 1903, '{85}', 108, 'https://en.wikipedia.org/wiki/Windscreen_wiper');
INSERT INTO inventions VALUES (91, 'Electrostatic precipitator', 'Электростатический фильтр', 'Предназначен для очистки воздуха от содержащихся в нём посторонних частиц', 1907, '{86}', 3, 'https://en.wikipedia.org/wiki/Electrostatic_precipitator');
INSERT INTO inventions VALUES (92, 'Paper shredder', 'Шредер', 'Офисное устройство (оргтехника) для измельчения бумаги в очень мелкие полоски или крошечные кусочки', 1909, '{87}', 285, 'https://en.wikipedia.org/wiki/Paper_shredder');
INSERT INTO inventions VALUES (93, 'Suppressor', 'Глушитель (оружейный)', 'Дульное механическое устройство стрелкового оружия, ослабляющее звук выстрела и скрывающее пламя пороховых газов', 1909, '{88}', 285, 'https://en.wikipedia.org/wiki/Suppressor');
INSERT INTO inventions VALUES (94, 'Headset', 'Головная гарнитура', 'Аксессуар систем связи, представляющий собой комбинацию головных телефонов с микрофоном', 1910, '{89}', 355, 'https://en.wikipedia.org/wiki/Headset_(audio)');
INSERT INTO inventions VALUES (95, 'Automobile self starter', 'Пусковая система двигателя внутреннего сгорания', 'Система, которая создаёт начальный вращающий моменти двигателю внутреннего сгорания для его старта', 1911, '{90}', 114, 'https://en.wikipedia.org/wiki/Starter_(engine)');
INSERT INTO inventions VALUES (96, 'Autopilot', 'Автопилот', 'Устройство или программно-аппаратный комплекс, ведущий транспортное средство по определённой, заданной ему траектории', 1912, '{91}', 279, 'https://en.wikipedia.org/wiki/Autopilot');
INSERT INTO inventions VALUES (97, 'Traffic light', 'Светофор', 'Оптическое устройство, подающее световые сигналы, регулирующие движение транспорта', 1912, '{92}', 221, 'https://en.wikipedia.org/wiki/Traffic_light');
INSERT INTO inventions VALUES (98, 'Single-sideband modulation', 'Однополосная модуляция', 'Разновидность амплитудной модуляции', 1915, '{93}', 312, 'https://en.wikipedia.org/wiki/Single-sideband_modulation');
INSERT INTO inventions VALUES (99, 'Supermarket', 'Супермаркет', 'Крупный универсам по продаже полного ассортимента продуктов питания и напитков, а также предметов домашнего хозяйства', 1916, '{94}', 233, 'https://en.wikipedia.org/wiki/Supermarket');
INSERT INTO inventions VALUES (100, 'Crystal oscillator', 'Кварцевый генератор', 'Автогенератор электромагнитных колебаний с колебательной системой, в состав которой входит кварцевый резонатор', 1918, '{95}', 357, 'https://en.wikipedia.org/wiki/Crystal_oscillator');
INSERT INTO inventions VALUES (101, 'Toaster', 'Тостер', 'Устройство с питанием от электросети, предназначенное для быстрого поджаривания плоских кусков хлеба', 1919, '{96}', 0, 'https://en.wikipedia.org/wiki/Toaster');
INSERT INTO inventions VALUES (102, 'Polygraph', 'Полиграф', 'Устройство, используемое для регистрации физиологических параметров, для оценки достоверности сообщённой информации', 1921, '{97}', 3, 'https://en.wikipedia.org/wiki/Polygraph');
INSERT INTO inventions VALUES (103, 'Flowchart', 'Блок-схема', 'Распространенный тип схем, описывающих алгоритмы, в которых отдельные шаги изображаются в виде блоков различной формы', 1921, '{98}', 0, 'https://en.wikipedia.org/wiki/Flowchart');
INSERT INTO inventions VALUES (104, 'Water skiing', 'Воднолыжный спорт', 'Передвижение по поверхности воды на специальной формы лыже, на тросе, соединённом с катером', 1922, '{99}', 362, 'https://en.wikipedia.org/wiki/Water_skiing');
INSERT INTO inventions VALUES (105, 'Audiometer', 'Аудиометр', 'Прибор для точного определения остроты слуха', 1922, '{100}', 98, 'https://en.wikipedia.org/wiki/Audiometer');
INSERT INTO inventions VALUES (106, 'Instant camera', 'Камера моментальной фотографии', 'Тип камеры, которая использует самопроявляющуюся пленку для создания фотоснимка вскоре после съемки.', 1923, '{101}', 285, 'https://en.wikipedia.org/wiki/Instant_camera');
INSERT INTO inventions VALUES (107, 'Liquid-fuel rocket', 'Жидкостный ракетный двигатель', 'Химический ракетный двигатель, использующий в качестве ракетного топлива жидкости, в том числе сжиженные газы', 1926, '{102}', 57, 'https://en.wikipedia.org/wiki/Liquid-propellant_rocket');
INSERT INTO inventions VALUES (108, 'Resonator guitar', 'Резонаторная гитара', 'От обычной акустической гитары отличается встроенным металлическим резонатором', 1927, '{103}', 283, 'https://en.wikipedia.org/wiki/Resonator_guitar');
INSERT INTO inventions VALUES (109, 'Bubble gum', 'Жевательная резинка', 'Кондитерское изделие, которое состоит из несъедобной эластичной основы и различных вкусовых и ароматических добавок', 1928, '{104}', 269, 'https://en.wikipedia.org/wiki/Bubble_gum');
INSERT INTO inventions VALUES (110, 'Electric razor', 'Электробритва', 'Электромеханическое устройство для бритья', 1928, '{105}', 0, 'https://en.wikipedia.org/wiki/Electric_razor');
INSERT INTO inventions VALUES (111, 'Freon', 'Фреоны', 'Фторсодержащие углеводороды, применяемые в качестве хладагентов, пропеллентов, вспенивателей, растворителей', 1929, '{90,106}', 114, 'https://en.wikipedia.org/wiki/Freon');
INSERT INTO inventions VALUES (112, 'Sunglasses', 'Солнцезащитные очки', 'Очки, надеваемые для защиты глаз от солнечного света и ультрафиолетовых лучей', 1929, '{107}', 0, 'https://en.wikipedia.org/wiki/Sunglasses');
INSERT INTO inventions VALUES (113, 'Car audio', 'Аудиосистема для автомобиля', 'Оборудование, установленное в автомобиле для прослушивание аудио.', 1930, '{108}', 279, 'https://en.wikipedia.org/wiki/Vehicle_audio');
INSERT INTO inventions VALUES (114, 'Bathysphere', 'Батисфера', 'Глубоководный аппарат в форме шара, опускаемый на тросе под воду с базового судна', 1930, '{109,110}', 285, 'https://en.wikipedia.org/wiki/Bathysphere');
INSERT INTO inventions VALUES (115, 'Electric guitar', 'Электрогитара', 'Гитара с электромагнитными звукоснимателями, преобразующими колебания мет. струн в колебания электрического тока', 1931, '{111,112}', 283, 'https://en.wikipedia.org/wiki/Electric_guitar');
INSERT INTO inventions VALUES (116, 'Radio telescope', 'Радиотелескоп', 'Астрономический инструмент для приёма собственного радиоизлучения небесных объектов ', 1932, '{113}', 370, 'https://en.wikipedia.org/wiki/Radio_telescope');
INSERT INTO inventions VALUES (117, 'Frequency modulation', 'Частотная модуляция', 'Вид аналоговой модуляции, при котором информационный сигнал управляет частотой несущего колебания', 1933, '{114}', 285, 'https://en.wikipedia.org/wiki/Frequency_modulation');
INSERT INTO inventions VALUES (118, 'Richter magnitude scale', 'Магнитуда землетрясения (шкала Рихтера)', 'Величина, характеризующая энергию, выделившуюся при землетрясении в виде сейсмических волн', 1935, '{115,116}', 44, 'https://en.wikipedia.org/wiki/Richter_magnitude_scale');
INSERT INTO inventions VALUES (119, 'Programming languages', 'Теория языка программирования', 'Область информатики, связанная с языками программирования и изучением их индивидуальных особенностей', 1936, '{117,118}', 291, 'https://en.wikipedia.org/wiki/Programming_language_theory');
INSERT INTO inventions VALUES (120, 'Bass guitar', 'Бас-гитара', 'Струнно-щипковый музыкальный инструмент, предназначенный для игры в басовом диапазоне', 1936, '{119}', 261, 'https://en.wikipedia.org/wiki/Bass_guitar');
INSERT INTO inventions VALUES (121, 'Digital computer', 'Компьютер', 'Устройство или система, способная выполнять заданную, чётко определённую, изменяемую последовательность операций', 1937, '{120}', 374, 'https://en.wikipedia.org/wiki/Computer');
INSERT INTO inventions VALUES (122, 'Fiberglass', 'Стеклопластик', 'Пластический материал, состоящий из стекловолокнистого наполнителя и связующего вещества', 1938, '{121}', 153, 'https://en.wikipedia.org/wiki/Fiberglass');
INSERT INTO inventions VALUES (123, 'Xerography', 'Электрография', 'Метод репрогра?фии, использующий для переноса тонера (сухих чернил) электрический заряд', 1938, '{122}', 285, 'https://en.wikipedia.org/wiki/Xerography');
INSERT INTO inventions VALUES (124, 'Automated teller machine', 'Банкомат', 'Комплекс, предназначенный для работы с наличнми денежными средствами с использованием платёжных карт', 1939, '{123}', 285, 'https://en.wikipedia.org/wiki/Automated_teller_machine');
INSERT INTO inventions VALUES (125, 'Vocoder', 'Вокодер', 'Устройство синтеза речи на основе произвольного сигнала с богатым спектром', 1939, '{124}', 285, 'https://en.wikipedia.org/wiki/Vocoder');
INSERT INTO inventions VALUES (126, 'Deodorant', 'Дезодорант', 'Косметическое изделие, предназначенное для маскировки, ослабления или устранения неприятных запахов', 1941, '{125}', 279, 'https://en.wikipedia.org/wiki/Deodorant');
INSERT INTO inventions VALUES (127, 'Electric guitar (solid body)', 'Электрогитара (цельнокорпусная)', 'Гитара с электромагнитными звукоснимателями, преобразующими колебания мет. струн в колебания электрического тока', 1941, '{126}', 285, 'https://en.wikipedia.org/wiki/Electric_guitar#Solid_body');
INSERT INTO inventions VALUES (128, 'Bazooka', 'Базука', 'Динамореактивный (без отдачи при выстреле) ручной противотанковый гранатомёт', 1942, '{377}', 284, 'https://en.wikipedia.org/wiki/Bazooka');
INSERT INTO inventions VALUES (129, 'Microwave oven', 'Микроволновая печь', 'Электроприбор, предназначенный для быстрого приготовления, подогрева или размораживания пищи', 1945, '{128}', 325, 'https://en.wikipedia.org/wiki/Microwave_oven');
INSERT INTO inventions VALUES (130, 'Cruise control', 'Круиз-контроль', 'Устройство, поддерживающее постоянную скорость автомобиля', 1945, '{129}', 379, 'https://en.wikipedia.org/wiki/Cruise_control');
INSERT INTO inventions VALUES (131, 'Space observatory', 'Астрономический спутник', 'Космический аппарат, сконструированный для проведения астрономических наблюдений из космоса', 1946, '{130}', 291, 'https://en.wikipedia.org/wiki/Space_telescope');
INSERT INTO inventions VALUES (132, 'Diaper (waterproof)', 'Подгузник', 'Вид нижнего белья, предназначенный для поглощения мочи и недопущения загрязнения верхней одежды', 1946, '{131}', 285, 'https://en.wikipedia.org/wiki/Diaper');
INSERT INTO inventions VALUES (133, 'Transistor', 'Транзистор', 'Радиоэлектронный компонент,  способный управлять значительным током в выходной цепи', 1947, '{132,133,134}', 409, 'https://en.wikipedia.org/wiki/Transistor');
INSERT INTO inventions VALUES (134, 'Windsurfing', 'Виндсерфинг', 'Вид парусного спорта, в основе которого лежит управление на водной поверхности лёгкой доской с установленным на ней парусом', 1948, '{135}', 381, 'https://en.wikipedia.org/wiki/Windsurfing');
INSERT INTO inventions VALUES (135, 'Cable television', 'Кабельное телевидение', 'Аналоговая модель телевизионного вещания', 1948, '{136}', 382, 'https://en.wikipedia.org/wiki/Cable_television');
INSERT INTO inventions VALUES (136, 'Video game', 'Компьютерная игра', 'Компьютерная программа, служащая для организации игрового процесса', 1948, '{137}', 386, 'https://en.wikipedia.org/wiki/Video_game');
INSERT INTO inventions VALUES (137, 'Radiocarbon dating', 'Радиоуглеродный анализ', 'Разновидность радиоизотопной датировки, применяемая для определения возраста биологических останков', 1949, '{138}', 279, 'https://en.wikipedia.org/wiki/Radiocarbon_dating');
INSERT INTO inventions VALUES (138, 'Ice resurfacer', 'Ледовый комбайн', 'Машина для восстановления льда на катках', 1949, '{139}', 389, 'https://en.wikipedia.org/wiki/Ice_resurfacer');
INSERT INTO inventions VALUES (139, 'Crash test dummy', 'Манекен для краш-тестов', 'Ростовая модель человека для использования в испытаниях техники и выявления степени опасности при её разрушении', 1949, '{140}', 0, 'https://en.wikipedia.org/wiki/Crash_test_dummy');
INSERT INTO inventions VALUES (140, 'Teleprompter', 'Телесуфлёр', 'Дисплей, отображающий текст речи или сценария для диктора или актёра незаметно для зрителя', 1950, '{141}', 264, 'https://en.wikipedia.org/wiki/Teleprompter');
INSERT INTO inventions VALUES (141, 'Correction fluid', 'Канцелярский корректор', 'Канцелярский инструмент, с помощью которого осуществляется исправление ошибок в тексте, корректировка написанного на бумаге', 1951, '{142}', 266, 'https://en.wikipedia.org/wiki/Correction_fluid');
INSERT INTO inventions VALUES (142, 'Airbag', 'Подушка безопасности', 'Система пассивной безопасности в транспортных средствах', 1952, '{143}', 392, 'https://en.wikipedia.org/wiki/Airbag');
INSERT INTO inventions VALUES (143, 'Barcode', 'Штрихкод', 'Графическая информация, наносимая на поверхность, предоставляющая возможность считывания её техническими средствами', 1952, '{144}', 393, 'https://en.wikipedia.org/wiki/Barcode');
INSERT INTO inventions VALUES (144, 'Heart-lung machine', 'Аппарат искусственного кровообращения', 'Специальное медицинское оборудование, обеспечивающее жизнедеятельность человека при частичной или полной невозможности выполнения функций сердца и/или лёгких', 1953, '{145}', 269, 'https://en.wikipedia.org/wiki/Cardiopulmonary_bypass');
INSERT INTO inventions VALUES (145, 'Marker pen', 'Фломастер (маркер)', 'Инструмент для письма и рисования при помощи краски, стекающей из резервуара к наконечнику из пористого материала', 1953, '{146}', 285, 'https://en.wikipedia.org/wiki/Marker_pen');
INSERT INTO inventions VALUES (146, 'Synthetic diamond', 'Синтетический алмаз', 'Алмазы, получаемые в результате искусственного процесса', 1954, '{147}', 396, 'https://en.wikipedia.org/wiki/Synthetic_diamond');
INSERT INTO inventions VALUES (147, 'Nuclear submarine', 'Атомная подводная лодка', 'Подводная лодка с ядерной силовой установкой', 1955, '{148}', 396, 'https://en.wikipedia.org/wiki/Nuclear_submarine');
INSERT INTO inventions VALUES (148, 'Hard disk drive', 'Жесткий диск', 'Запоминающее устройство, основанное на принципе магнитной записи', 1955, '{149}', 216, 'https://en.wikipedia.org/wiki/Hard_disk_drive');
INSERT INTO inventions VALUES (149, 'Kart racing', 'Картинг', 'Вид спорта и развлечения, гонки на картах — простейших гоночных автомобилях без кузова', 1956, '{150}', 283, 'https://en.wikipedia.org/wiki/Kart_racing');
INSERT INTO inventions VALUES (150, 'Industrial robot', 'Промышленный робот', 'Предназначенный для выполнения двигательных и управляющих функций в производственном процессе манипуляционный робот, т. е. автоматическое устройство, состоящее из манипулятора и перепрограммируемого устройства управления, которое формирует управляющие воздействия, задающие требуемые движения исполнительных органов манипулятора.', 1956, '{151,152}', 398, 'https://en.wikipedia.org/wiki/Industrial_robot');
INSERT INTO inventions VALUES (151, 'Videotape', 'Видеопленка (видеокассета)', 'Картридж для хранения магнитной ленты, предназначенной для наклонно-строчной видеозаписи. Является разновидностью носителя информации и применяется для записи и воспроизведения телевизионного изображения и звукового сопровождения посредством видеомагнитофона или видеокамеры.', 1956, '{153,154}', 380, 'https://en.wikipedia.org/wiki/Videotape');
INSERT INTO inventions VALUES (152, 'Laser', 'Лазер', 'Устройство, преобразующее энергию накачки (световую, электрическую, тепловую, химическую и др.) в энергию когерентного, монохроматического, поляризованного и узконаправленного потока излучения.', 1957, '{155}', 285, 'https://en.wikipedia.org/wiki/Laser');
INSERT INTO inventions VALUES (153, 'Gamma camera', 'Гамма-камера', 'Основной инструмент современной радионуклидной диагностики. Гамма-камеры предназначены для визуализации и исследования кинетики радиофармпрепаратов во внутренних органах и физиологических системах организма пациента с целью ранней диагностики онкологических, сердечно-сосудистых и других заболеваний человека.', 1957, '{156}', 3, 'https://en.wikipedia.org/wiki/Gamma_camera');
INSERT INTO inventions VALUES (154, 'Integrated circuit', 'Интегральная схема', 'Микроэлектронное устройство — электронная схема произвольной сложности (кристалл), изготовленная на полупроводниковой подложке (пластине или плёнке) и помещённая в неразборный корпус или без такового, в случае вхождения в состав микросборки.', 1958, '{157}', 266, 'https://en.wikipedia.org/wiki/Integrated_circuit');
INSERT INTO inventions VALUES (155, 'Spandex', 'Полиуретановые волокна', 'Синтетическая нить, получаемая на основе полиуретановых каучуков', 1959, '{158}', 403, 'https://en.wikipedia.org/wiki/Spandex');
INSERT INTO inventions VALUES (156, 'Magnetic stripe card', 'Карта с магнитной полосой', 'Тип карт, отличающийся наличием магнитной полосы. Магнитная полоса предназначена для хранения какой?либо информации. Запись информации выполняется путём намагничивания крошечных частиц, находящихся на поверхности полоски и содержащих железо (магнитный материал). Чтение информации выполняется путём проведения полосы по магнитной головке.', 1960, '{159}', 406, 'https://en.wikipedia.org/wiki/Magnetic_stripe_card');
INSERT INTO inventions VALUES (157, 'Gas laser', 'Газовый лазер', 'Лазер, в котором в качестве активной среды используется вещество, находящееся в газообразном состоянии (в отличие от твёрдых тел в твердотельных лазерах и жидкостей в лазерах на красителях).', 1960, '{160,161}', 409, 'https://en.wikipedia.org/wiki/Gas_laser');
INSERT INTO inventions VALUES (158, 'Spreadsheet (electronic)', 'Электронная таблица', 'Компьютерная программа, позволяющая проводить вычисления с данными, представленными в виде двумерных массивов, имитирующих бумажные таблицы[2]. Некоторые программы организуют данные в «листы», предлагая, таким образом, третье измерение.', 1961, '{162}', 3, 'https://en.wikipedia.org/wiki/Spreadsheet');
INSERT INTO inventions VALUES (159, 'Wearable computer', 'Носимый компьютер', 'Компьютер, который можно носить с собой на теле (что-то среднее между наручными часами и смартфоном). На данный момент нет чёткой спецификации и стандартов для данного устройства.', 1961, '{163,164}', 316, 'https://en.wikipedia.org/wiki/Wearable_computer');
INSERT INTO inventions VALUES (160, 'Communications satellite', 'Спутник связи', 'Искусственный спутник Земли, специализированный для ретрансляции радиосигнала между точками на поверхности Земли, не имеющими видимости прямого типа.', 1962, '{165}', 349, 'https://en.wikipedia.org/wiki/Communications_satellite');
INSERT INTO inventions VALUES (161, 'Light-emitting diode', 'Светодиод', 'Полупроводниковый прибор с электронно-дырочным переходом, создающий оптическое излучение при пропускании через него электрического тока в прямом направлении', 1962, '{166}', 197, 'https://en.wikipedia.org/wiki/Light-emitting_diode');
INSERT INTO inventions VALUES (162, 'Computer mouse', 'Компьютерная мышь', 'Координатное устройство для управления курсором и отдачи различных команд компьютеру. Управление курсором осуществляется путём перемещения мыши по поверхности стола или коврика для мыши.', 1963, '{167}', 414, 'https://en.wikipedia.org/wiki/Computer_mouse');
INSERT INTO inventions VALUES (163, 'BASIC', 'Бейсик', 'Семейство высокоуровневых языков программирования.', 1963, '{168,169}', 374, 'https://en.wikipedia.org/wiki/BASIC');
INSERT INTO inventions VALUES (164, 'Plasma display', 'Плазменная панель', 'Устройство отображения информации, монитор, основанный на явлении свечения люминофора под воздействием ультрафиолетовых лучей, возникающих при электрическом разряде в ионизированном газе, иначе говоря в плазме.', 1964, '{170}', 417, 'https://en.wikipedia.org/wiki/Plasma_display');
INSERT INTO inventions VALUES (165, 'Moog synthesizer', 'Синтезатор Муга', 'Аналоговый синтезатор, спроектированный Робертом Мугом', 1964, '{171}', 285, 'https://en.wikipedia.org/wiki/Moog_synthesizer');
INSERT INTO inventions VALUES (166, 'Liquid-crystal display', 'Жидкокристаллический дисплей', 'Плоский дисплей на основе жидких кристаллов, а также устройство (монитор, телевизор) на основе такого дисплея.', 1964, '{172}', 291, 'https://en.wikipedia.org/wiki/Liquid-crystal_display');
INSERT INTO inventions VALUES (167, 'Kevlar', 'Кевлар', 'Арамидное волокно (полипарафенилен-терефталамид), выпускаемого фирмой DuPont. Кевлар обладает высокой прочностью.', 1965, '{173}', 421, 'https://en.wikipedia.org/wiki/Kevlar');
INSERT INTO inventions VALUES (218, 'Instant mashed potatoes', 'Пюре быстрого приготовления', NULL, 1960, '{233}', 254, 'https://en.wikipedia.org/wiki/Instant_mashed_potatoes');
INSERT INTO inventions VALUES (219, 'Pablum', 'Паблум', 'Разновидность детского питания.', 1935, '{234,235,236}', 282, 'https://en.wikipedia.org/wiki/Pablum');
INSERT INTO inventions VALUES (168, 'Cordless telephone', 'Радиотелефон', 'Общее название средств передачи речевого сигнала через радиосвязь. В быту радиотелефоном называют телефонный аппарат с беспроводной связью трубки с базой.', 1965, '{174}', 66, 'https://en.wikipedia.org/wiki/Cordless_telephone');
INSERT INTO inventions VALUES (169, 'Compact disc', 'Компакт-диск', 'Оптический носитель информации в виде пластикового диска с отверстием в центре, процесс записи и считывания информации которого осуществляется при помощи лазера.', 1965, '{175}', 423, 'https://en.wikipedia.org/wiki/Compact_disc');
INSERT INTO inventions VALUES (170, 'Dynamic random access memory', 'Динамическая память с произвольным доступом', 'Тип компьютерной памяти, отличающийся использованием полупроводниковых материалов, энергозависимостью и возможностью доступа к данным, хранящимся в произвольных ячейках памяти (см. запоминающее устройство с произвольным доступом). Модули памяти с памятью такого типа широко используются в современных компьютерах в качестве оперативных запоминающих устройств (ОЗУ), также используются в качестве устройств постоянного хранения информации в системах, требовательных к задержкам.', 1966, '{176}', 425, 'https://ru.wikipedia.org/wiki/DRAM');
INSERT INTO inventions VALUES (171, 'Calculator', 'Калькулятор', 'Электронное вычислительное устройство для выполнения операций над числами или алгебраическими формулами.', 1967, '{157}', 266, 'https://en.wikipedia.org/wiki/Calculator');
INSERT INTO inventions VALUES (172, 'Virtual reality', 'Виртуальная реальность', 'Созданный техническими средствами мир (объекты и субъекты), передаваемый человеку через его ощущения: зрение, слух, обоняние, осязание и другие.', 1968, '{177,178}', 316, 'https://en.wikipedia.org/wiki/Virtual_reality');
INSERT INTO inventions VALUES (173, 'Lunar Module', 'Лунный модуль', 'Посадочный модуль, часть корабля «Аполлон», построенный для американской программы «Аполлон» компанией Grumman Corporation для экипажа из двух человек с целью доставки с лунной орбиты на поверхность Луны и обратно.', 1969, '{179}', 285, 'https://en.wikipedia.org/wiki/Apollo_Lunar_Module');
INSERT INTO inventions VALUES (174, 'Laser printing', 'Лазерный принтер', 'Один из видов принтеров, позволяющий быстро изготавливать высококачественные отпечатки текста и графики на обычной (офисной) бумаге.', 1969, '{180}', 397, 'https://en.wikipedia.org/wiki/Laser_printing');
INSERT INTO inventions VALUES (175, 'Chapman Stick', 'Стик Чепмена', 'Струнный музыкальный инструмент со звукоснимателями, разновидность электрогитары.', 1969, '{181}', 0, 'https://en.wikipedia.org/wiki/Chapman_Stick');
INSERT INTO inventions VALUES (176, 'Wireless local area network', 'Беспроводная локальная сеть', 'Локальная сеть, построенная на основе беспроводных технологий.', 1970, '{182}', 260, 'https://en.wikipedia.org/wiki/Wireless_LAN');
INSERT INTO inventions VALUES (177, 'Personal computer', 'Персональный компьютер', 'Настольная микро-ЭВМ, имеющая эксплуатационные характеристики бытового прибора и универсальные функциональные возможности', 1971, '{183}', 283, 'https://en.wikipedia.org/wiki/Personal_computer');
INSERT INTO inventions VALUES (178, 'Microprocessor', 'Микропроцессор', 'Процессор (устройство, отвечающее за выполнение арифметических, логических операций и операций управления, записанных в машинном коде), реализованный в виде одной микросхемы или комплекта из нескольких специализированных микросхем.', 1971, '{184,185,186}', 427, 'https://en.wikipedia.org/wiki/Microprocessor');
INSERT INTO inventions VALUES (179, 'Email', 'Электронная почта', 'Технология и служба по пересылке и получению электронных сообщений (называемых «письма», «электронные письма» или «сообщения») между пользователями компьютерной сети (в том числе — Интернета).', 1971, '{187}', 316, 'https://en.wikipedia.org/wiki/Email');
INSERT INTO inventions VALUES (180, 'Video game console', 'Игровая приставка', ' Специализированное электронное устройство, предназначенное для видеоигр. ', 1972, '{188}', 430, 'https://en.wikipedia.org/wiki/Video_game_console');
INSERT INTO inventions VALUES (181, 'Magnetic resonance imaging', 'Магнитно-резонансная томография', 'Способ получения томографических медицинских изображений для исследования внутренних органов и тканей с использованием явления ядерного магнитного резонанса. ', 1972, '{189}', 285, 'https://en.wikipedia.org/wiki/Magnetic_resonance_imaging');
INSERT INTO inventions VALUES (182, 'Mobile phone', 'Сотовый телефон', 'Мобильный телефон, предназначенный для работы в сетях сотовой связи, использует приёмопередатчик радиодиапазона и традиционную телефонную коммутацию для осуществления телефонной связи на территории зоны покрытия сотовой сети.', 1973, '{190}', 431, 'https://en.wikipedia.org/wiki/Mobile_phone');
INSERT INTO inventions VALUES (183, 'Post-it note', 'Бумага для заметок', 'Небольшие листки, на которые с одной стороны узкой полоской нанесён специальный клей, обычно жёлтого цвета. Они склеены в виде блокнота, отдельные листки из которого легко отрываются и могут быть приклеены к каким-либо предметам, а в дальнейшем сняты с них, не оставив никаких следов. ', 1974, '{191,192}', 432, 'https://en.wikipedia.org/wiki/Post-it_note');
INSERT INTO inventions VALUES (202, 'Segway PT', 'Сегвей', 'Электрическое самобалансирующееся транспортное средство с двумя колёсами, расположенными по обе стороны от водителя, внешне напоминающее колесницу.', 1994, '{213}', 58, 'https://en.wikipedia.org/wiki/Segway_PT');
INSERT INTO inventions VALUES (184, 'Digital camera', 'Цифровой фотоаппарат', 'Фотоаппарат, в котором для записи оптического изображения вместо светочувствительного материала используется полупроводниковая фотоматрица и цифровое запоминающее устройство. Аналоговый сигнал с матрицы с помощью АЦП преобразуются в цифровые файлы и записывается на накопитель в фотоаппарате или другом внешнем устройстве.', 1975, '{193}', 166, 'https://en.wikipedia.org/wiki/Digital_camera');
INSERT INTO inventions VALUES (185, 'Ethernet', 'Ethernet', 'Семейство технологий пакетной передачи данных для компьютерных сетей.', 1975, '{194}', 397, 'https://en.wikipedia.org/wiki/Ethernet');
INSERT INTO inventions VALUES (186, 'Human-powered aircraft', 'Мускулолёт', 'Летательный аппарат, приводимый в действие мускульной энергией пилота. Аппараты могут быть выполнены в виде самолёта, вертолёта и махолёта.', 1977, '{195}', 44, 'https://en.wikipedia.org/wiki/Human-powered_aircraft');
INSERT INTO inventions VALUES (187, 'Bulletin board system', 'BBS', 'Широко используемый во времена редкости кабельных компьютерных сетей способ общения пользователей компьютеров через коммутируемые телефонные сети.', 1978, '{196}', 279, 'https://en.wikipedia.org/wiki/Bulletin_board_system');
INSERT INTO inventions VALUES (188, 'Winglets', 'Законцовка крыла', 'Оконечная часть конструкции крыла, оперения или лопастей воздушного винта у летательных аппаратов.', 1979, '{197}', 0, 'https://en.wikipedia.org/wiki/Wingtip_device');
INSERT INTO inventions VALUES (189, 'Control-Alt-Delete ', 'Control-Alt-Delete (комбинация)', 'Комбинация компьютерных клавиш для IBM-совместимых компьютеров, вызываемая нажатием клавиши Delete при удерживании клавиш Control и Alt: Ctrl+Alt+Delete. Функция комбинации клавиш различна, но обычно она прерывает или облегчает прерывание функции.', 1981, '{198}', 285, 'https://en.wikipedia.org/wiki/Control-Alt-Delete');
INSERT INTO inventions VALUES (190, 'Space Shuttle', 'Спейс шаттл (Космический челнок)', 'Американский многоразовый транспортный космический корабль. Подразумевалось, что шаттлы будут «сновать, как челноки» между околоземной орбитой и Землёй, доставляя полезные грузы в обоих направлениях.', 1981, '{199}', 284, 'https://en.wikipedia.org/wiki/Space_shuttle');
INSERT INTO inventions VALUES (191, 'Internet', 'Интернет', 'Всемирная система объединённых компьютерных сетей для хранения и передачи информации. Построена на базе стека протоколов TCP/IP. ', 1983, '{200,201}', 0, 'https://en.wikipedia.org/wiki/Internet');
INSERT INTO inventions VALUES (192, 'LCD projector', 'Жидкокристаллический проектор', 'Устройство, проецирующее на экран изображение, созданное одной или несколькими жидкокристаллическими матрицами.', 1984, '{202}', 285, 'https://en.wikipedia.org/wiki/LCD_projector');
INSERT INTO inventions VALUES (193, 'Atomic force microscope', 'Сканирующий атомно-силовой микроскоп', 'Сканирующий зондовый микроскоп высокого разрешения. Используется для определения рельефа поверхности с разрешением от десятков ангстрем вплоть до атомарного', 1986, '{203,204,205}', 0, 'https://en.wikipedia.org/wiki/Atomic-force_microscopy');
INSERT INTO inventions VALUES (194, 'Perl', 'Perl', 'Высокоуровневый интерпретируемый динамический язык программирования общего назначения, созданный Ларри Уоллом, лингвистом по образованию. ', 1987, '{206}', 438, 'https://en.wikipedia.org/wiki/Perl');
INSERT INTO inventions VALUES (197, 'Firewall', 'Файрвол', 'Программный или программно-аппаратный элемент компьютерной сети, осуществляющий контроль и фильтрацию проходящего через него сетевого трафика в соответствии с заданными правилами.', 1988, '{207,208}', 409, 'https://en.wikipedia.org/wiki/Firewall_(computing)');
INSERT INTO inventions VALUES (198, 'ZIP file format', 'ZIP', 'Популярный формат архивации файлов и сжатия данных без потерь.', 1989, '{209}', 235, 'https://en.wikipedia.org/wiki/Zip_(file_format)');
INSERT INTO inventions VALUES (199, 'Ant robotics', 'Разновидность групповой робототехники', 'Групповая робототехника представляет собой новый подход к координации систем многих роботов, которые состоят из большого числа в основном простых физических роботов. Предполагается, что желаемое коллективное поведение возникает из взаимодействия роботов между собой и их взаимодействия с окружающей средой. Такой подход относится к научному направлению по искусственному роевому интеллекту, возникшему при проведении биологических исследований насекомых, в частности, муравьёв, пчёл, а также при исследовании в других областях природы, где имеет место роевое поведение.', 1991, '{210}', 316, 'https://en.wikipedia.org/wiki/Ant_robotics');
INSERT INTO inventions VALUES (200, 'CMOS image sensor', 'КМОП-матрица', 'Светочувствительная матрица, выполненная на основе КМОП-технологии. В КМОП-матрицах используются полевые транзисторы с изолированным затвором с каналами разной проводимости.', 1994, '{211}', 44, 'https://en.wikipedia.org/wiki/Active_pixel_sensor');
INSERT INTO inventions VALUES (201, 'DNA computing', 'ДНК-компьютер', 'Вычислительная система, использующая вычислительные возможности молекул ДНК.', 1994, '{212}', 283, 'https://en.wikipedia.org/wiki/DNA_computing');
INSERT INTO inventions VALUES (220, 'Yukon Gold ', 'Юкон Голд', 'Сорт картофеля.', 1966, '{237}', 449, 'https://en.wikipedia.org/wiki/Yukon_Gold_(potato)');
INSERT INTO inventions VALUES (203, 'Scroll wheel', 'Колёсико прокрутки', 'Конструктивный элемент компьютерной мыши, позволяющий продвигать изображение по экрану при неподвижном указателе)', 1995, '{214}', 0, 'https://en.wikipedia.org/wiki/Scroll_wheel');
INSERT INTO inventions VALUES (204, 'JavaScript', 'JavaScript', 'Прототипно-ориентированный сценарный язык программирования. JavaScript обычно используется как встраиваемый язык для программного доступа к объектам приложений. Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам.', 1995, '{312}', 427, 'https://en.wikipedia.org/wiki/JavaScript');
INSERT INTO inventions VALUES (205, 'Adobe Flash', 'Adobe Flash', 'Мультимедийная платформа компании Adobe Systems для создания веб-приложений или мультимедийных презентаций. Широко используется для создания рекламных баннеров, анимации, игр, а также воспроизведения на веб-страницах видео- и аудиозаписей.', 1996, '{216}', 263, 'https://en.wikipedia.org/wiki/Adobe_Flash');
INSERT INTO inventions VALUES (206, 'Torino scale', 'Туринская шкала', 'Таблица, показывающая степень опасности, исходящую от определённого небесного объекта (например, астероида). Шкала имеет субъективную оценку, чем отличается, например, от шкалы Палермо.', 1999, '{217}', 316, 'https://en.wikipedia.org/wiki/Torino_scale');
INSERT INTO inventions VALUES (207, 'iBOT', 'iBOT', 'Самобалансирующее инвалидное кресло с гироскопом.', 1999, '{213}', 0, 'https://en.wikipedia.org/wiki/IBOT');
INSERT INTO inventions VALUES (208, 'Fermionic condensate', 'Фермионный конденсат', 'Шестое состояние вещества (после таких состояний как твёрдое тело, жидкость, газ, плазма и конденсат Бозе-Эйнштейна).', 2003, '{218}', 0, 'https://en.wikipedia.org/wiki/Fermionic_condensate');
INSERT INTO inventions VALUES (209, 'Nanowire battery', 'Нанопроводниковый аккумулятор', 'Вид литий-ионного аккумулятора, изобретённый группой под руководством д-ра Йи Кю (Yi Cui) в Стэнфордском университете в 2007 г. Изобретение состоит в замене традиционного графитового анода аккумулятора на анод из нержавеющей стали, покрытый кремниевым нанопроводником. ', 2007, '{219}', 380, 'https://en.wikipedia.org/wiki/Nanowire_battery');
INSERT INTO inventions VALUES (210, 'Bionic contact lens', 'Бионические контактные линзы', 'Проектируемый (разрабатываемый, но не доведенный до массового производства) виртуальный дисплей, который может иметь множество применений, от оказания помощи слабовидящим до индустрии видеоигр. Устройство будет иметь вид обычной контактной линзы с включениями бионических технологий. Линзы будут использовать функциональные электронные схемы и инфракрасный свет чтобы создать виртуальный дисплей.', 2008, '{220}', 261, 'https://en.wikipedia.org/wiki/Bionic_contact_lens');
INSERT INTO inventions VALUES (211, 'Key frame animation ', 'Мультипликация по ключевым кадрам', 'Технология создания мультипликации, при которой первоначально создаются основные (ключевые или компоновочные) рисунки, а затем добавляются промежуточные между ними, называемые фазами.', 1970, '{221,222}', 0, 'https://en.wikipedia.org/wiki/Key_frame');
INSERT INTO inventions VALUES (212, 'Multi-dynamic image technique', 'Вариоскопический кинематограф', 'Вид кинематографа, в котором размеры изображения и соотношение сторон кадра изменяются во время киносеанса.Изменение размера и пропорций кадра достигаются кашированием при печати фильмокопий. ', 1968, '{223}', 282, 'https://en.wikipedia.org/wiki/Multi-dynamic_image_technique');
INSERT INTO inventions VALUES (213, 'IMax Movie System', 'IMAX', 'Широкоформатная кинематографическая система, на которой основаны ряд технологий кинопоказа и устройство сети кинотеатров по всему миру.', 1967, '{224,225,226}', 282, 'https://en.wikipedia.org/wiki/IMAX');
INSERT INTO inventions VALUES (214, 'Trackball', 'Трекбол', 'Указательное устройство ввода информации об относительном перемещении для компьютера. Аналогично мыши по принципу действия и по функциям. Трекбол функционально представляет собой перевернутую механическую (шариковую) мышь. Шар находится сверху или сбоку, и пользователь может вращать его ладонью или пальцами, при этом не перемещая корпус устройства.', 1952, '{227,228,229}', 0, 'https://en.wikipedia.org/wiki/Trackball');
INSERT INTO inventions VALUES (215, 'Marquis wheat', 'Сорт пшеницы Marquis', 'Сорт пшеницы высокого качества.', 1904, '{230}', 0, 'https://en.wikipedia.org/wiki/Marquis_wheat');
INSERT INTO inventions VALUES (216, 'McIntosh Red', 'Мекинтош', 'Популярный в Северной Америке сорт яблок осенне-зимнего срока созревания.', 1811, '{231}', 444, 'https://en.wikipedia.org/wiki/McIntosh_(apple)');
INSERT INTO inventions VALUES (217, 'Peanut butter', 'Арахисовая паста', 'Разновидность бобовой пасты, намазка из поджаренных бобов арахиса, чаще всего с добавлением растительного масла. Традиционный продукт кухни США, где 24 января провозглашено Национальным днём арахисовой пасты.', 1884, '{232}', 275, 'https://en.wikipedia.org/wiki/Peanut_butter');
INSERT INTO inventions VALUES (221, 'Walkie-talkie', 'Рация', 'Портативная переносная рация.', 1939, '{238,239}', 0, 'https://en.wikipedia.org/wiki/Walkie-talkie');
INSERT INTO inventions VALUES (222, 'Amplitude modulation', 'Амплитудная модуляция', 'Вид модуляции, при которой изменяемым параметром несущего сигнала является его амплитуда.', 1906, '{240}', 0, 'https://en.wikipedia.org/wiki/Amplitude_modulation');
INSERT INTO inventions VALUES (224, 'Pager', 'Пейджер', 'Приёмник персонального вызова. Сообщения на него передаются по пейджинговой сети. Для того чтобы отправить почту на пейджер, надо набрать телефон оператора, сообщить номер или название абонента и продиктовать сообщение.', 1949, '{239}', 282, 'https://en.wikipedia.org/wiki/Pager');
INSERT INTO inventions VALUES (225, 'Brunton compass', 'Компас Брантона', 'Карманный компас с визиром и зеркальным отражением для измерения углов и определения направления', 1894, '{242}', 400, 'https://en.wikipedia.org/wiki/Brunton_compass');
INSERT INTO inventions VALUES (226, 'Radiotelephone', 'Радиофон', 'Коммуникационная система передачи голоса с помощью радио.', 1901, '{240}', 0, 'https://en.wikipedia.org/wiki/Radiotelephone#Marine_use');
INSERT INTO inventions VALUES (227, 'Fathometer ', 'Гидролокатор', 'Средство звукового обнаружения подводных объектов с помощью акустического излучения.', 1919, '{240}', 0, 'https://en.wikipedia.org/wiki/Echo_sounding');
INSERT INTO inventions VALUES (228, 'Hot wire barretter', 'Бареттер Фессендена', 'Разновидность демодулятора,  использовавшегося в первых радиоприёмниках для приёма радиосигналов.', 1902, '{240}', 0, 'https://en.wikipedia.org/wiki/Hot_wire_barretter');
INSERT INTO inventions VALUES (229, 'The wheelchair accessible bus', 'Автобус, приспособленный для инвалидов в креслах', NULL, 1947, '{243}', 454, NULL);
INSERT INTO inventions VALUES (230, 'The separable baggage check', 'Багажная бирка', 'Багажная бирка или багажная квитанция — традиционно использовались автобусными, железнодорожными и авиакомпаниями для того, чтобы отследить зарегистрированный багаж пассажиров от момента сдачи багажа до конечного пункта. ', 1882, '{244}', 455, 'https://en.wikipedia.org/wiki/Bag_tag');
INSERT INTO inventions VALUES (231, 'Hydrofoil boat', 'Судно на подводных крыльях', 'Тип скоростного судна с динамическим принципом поддержания, у которого под корпусом расположены подводные крылья.', 1908, '{245,51}', 0, 'https://en.wikipedia.org/wiki/Hydrofoil');
INSERT INTO inventions VALUES (232, 'Avro Canada C102 Jetliner', 'Avro Canada C102 Jetliner', 'Прототип среднемагистрального реактивного пассажирского самолёта построенный канадской авиастроительной компанией Авро Канада Лимитед в 1949 году. Второй в мире и первый в Северной Америке летающий реактивный авиалайнер.', 1949, '{246}', 282, 'https://en.wikipedia.org/wiki/Avro_Canada_C102_Jetliner');
INSERT INTO inventions VALUES (233, 'Variable-pitch propeller', 'Винт регулируемого шага', 'Винтовой движитель, угол атаки лопастей которого не задан при производстве, а может изменяться непосредственно в процессе эксплуатации.', 1927, '{247}', 456, 'https://en.wikipedia.org/wiki/Variable-pitch_propeller');
INSERT INTO inventions VALUES (234, 'Snowmobile', 'Снегоход', 'Механическое транспортное средство, предназначенное для движения по снегу.', 1937, '{248}', 457, 'https://en.wikipedia.org/wiki/Snowmobile');
INSERT INTO inventions VALUES (235, 'Uno dicycle ', 'Уно (дицикл)', 'Транспортное средство на двух колесах, которые расположены параллельно', 2006, '{249}', 458, 'https://en.wikipedia.org/wiki/Uno_(dicycle)');
INSERT INTO inventions VALUES (236, 'Electric wheelchair', 'Инвалидная колеска с электроприводом', 'Инвалидная колеска с электроприводом', 1952, '{250}', 254, 'https://en.wikipedia.org/wiki/Wheelchair#Electric-powered_wheelchairs');
INSERT INTO inventions VALUES (237, 'Prosthetic hand ', 'Механический протез руки', NULL, 1971, '{251}', 0, 'https://en.wikipedia.org/wiki/Prosthesis#Hands');
INSERT INTO inventions VALUES (238, 'Compound steam engine', 'Компаунд-машина', 'Паровая машина двойного расширения пара. Компаунд-машина имеет два (или больше) рабочих цилиндра разного диаметра. Свежий пар из котла поступает в меньший цилиндр высокого давления. Отработав там (первое расширение), пар перепускается в больший низкого давления. Такая схема работы позволяет более полно использовать энергию пара и повысить коэффициент полезного действия двигателя.', 1842, '{252}', 456, 'https://en.wikipedia.org/wiki/Compound_steam_engine');
INSERT INTO inventions VALUES (239, 'Electric car heater', 'Электрический обогреватель автомобиля', NULL, 1890, '{235}', 254, NULL);
INSERT INTO inventions VALUES (240, 'Snow blower', 'Снегоочиститель ', 'Машина для очистки дороги от снега.', 1925, '{254}', 275, 'https://en.wikipedia.org/wiki/Snow_blower');
INSERT INTO inventions VALUES (241, 'The steam-powered foghorn', 'Паровая сирена', 'Сигнальное устройство на паровой тяге, подающее звуковые сигналы судам во время тумана.', 1854, '{255}', 456, 'https://en.wikipedia.org/wiki/Foghorn');
INSERT INTO inventions VALUES (242, 'Rotary snowplow', 'Роторный снегоочиститель', 'Машина для уборки снега с железнодорожный путей.', 1869, '{256,257}', 460, 'https://en.wikipedia.org/wiki/Rotary_snowplow');
INSERT INTO inventions VALUES (243, 'Gas mask(1)', 'Противогаз(1)', 'Средство защиты органов дыхания, зрения и кожи лица.', 1915, '{258}', 257, 'https://en.wikipedia.org/wiki/Gas_mask');
INSERT INTO inventions VALUES (282, 'Padel ', 'Падель', 'Игра с мячом и ракеткой, схожая с теннисом и сквошем.', 1969, '{298}', 242, 'https://en.wikipedia.org/wiki/Padel_(sport)');
INSERT INTO inventions VALUES (244, 'G-suit', 'Противоперегрузочный костюм', 'Вид лётного снаряжения, предназначенный для повышения устойчивости организма к воздействию перегрузок, представляет собой одежду типа комбинезона, конструкция которого предусматривает возможность создания внешнего давления с целью противодействия смещению крови в сосуды нижних конечностей и живота.', 1941, '{259}', 282, 'https://en.wikipedia.org/wiki/G-suit');
INSERT INTO inventions VALUES (245, 'ASDIC', 'ASDIC', 'Разновидность гидролокатора, средства звукового обнаружения подводных объектов с помощью акустического излучения.', 1916, '{260}', 0, 'https://en.wikipedia.org/wiki/Sonar');
INSERT INTO inventions VALUES (246, 'Lacrosse', 'Лакросс', 'Контактная спортивная игра между двумя командами, с использованием небольшого резинового мяча (62.8-64.77 мм, 140-146 грамм) и клюшки с длинной рукояткой, называющейся стик (lacrosse stick или crosse). ', 1860, '{261}', 275, 'https://en.wikipedia.org/wiki/Lacrosse');
INSERT INTO inventions VALUES (247, 'Basketball', 'Баскетбол', 'Спортивная командная игра с мячом.В баскетбол играют две команды, каждая из которых состоит из пяти полевых игроков (всего в каждой команде по 12 человек, замены не ограничены). Цель каждой команды — забросить руками мяч в кольцо с сеткой (корзину) соперника и помешать другой команде завладеть мячом и забросить его в свою корзину. ', 1891, '{262}', 14, 'https://en.wikipedia.org/wiki/Basketball');
INSERT INTO inventions VALUES (248, 'Ice hockey', 'Хоккей с шайбой', 'Командная спортивная игра на льду, заключающаяся в противоборстве двух команд на коньках, которые, передавая шайбу клюшками, стремятся забросить её наибольшее количество раз в ворота соперника и не пропустить в свои.', 0, '{0}', 0, 'https://en.wikipedia.org/wiki/Ice_hockey');
INSERT INTO inventions VALUES (249, 'Table hockey game ', 'Настольный хоккей', 'Игра для двух человек, имитирующая хоккей с шайбой.', 1936, '{263}', 282, 'https://en.wikipedia.org/wiki/Table_hockey_games');
INSERT INTO inventions VALUES (250, 'Goaltender mask', 'Маска вратаря', 'Маска, защищающая от травм лицо хоккейного вратаря.', 1959, '{264}', 275, 'https://en.wikipedia.org/wiki/Goaltender_mask');
INSERT INTO inventions VALUES (251, 'Five-pin bowling', '5-кегельный боулинг', 'Канадская разновидность боулинга.', 1909, '{265}', 282, 'https://en.wikipedia.org/wiki/Five-pin_bowling');
INSERT INTO inventions VALUES (252, 'Abdominizer', 'Абдоминайзер', 'Тренажер для брюшного пресса.', 1984, '{266}', 0, 'https://en.wikipedia.org/wiki/Abdominizer');
INSERT INTO inventions VALUES (253, 'Trivial Pursuit', 'Trivial Pursuit', 'Настольная игра-викторина.', 1979, '{267,268}', 275, 'https://en.wikipedia.org/wiki/Trivial_Pursuit');
INSERT INTO inventions VALUES (254, 'Insulin', 'Выделение инсулина', 'Гормон пептидной природы, образуется в бета-клетках островков Лангерганса поджелудочной железы. Оказывает многогранное влияние на обмен практически во всех тканях. Основное действие инсулина заключается в снижении концентрации глюкозы в крови. ', 1922, '{269,270,271}', 282, 'https://en.wikipedia.org/wiki/Insulin');
INSERT INTO inventions VALUES (255, 'Electron microscope', 'Электронный микроскоп', 'Прибор, позволяющий получать изображение объектов с максимальным увеличением до 106 раз, благодаря использованию, в отличие от оптического микроскопа, вместо светового потока, пучка электронов с энергиями 200 эВ — 400 кэВ и более (например, просвечивающие электронные микроскопы высокого разрешения с ускоряющим напряжением 1 МВ).', 1939, '{272,273,274}', 282, 'https://en.wikipedia.org/wiki/Electron_microscope');
INSERT INTO inventions VALUES (256, 'Process to extract Bromine ', 'Метод получения брома', NULL, 1890, '{275}', 472, 'https://en.wikipedia.org/wiki/Bromine');
INSERT INTO inventions VALUES (257, 'Process for producing Calcium Carbide', 'Метод получения карбида кальция', 'Получение карбида кальция для производства ацетилена', 1892, '{276}', 0, 'https://en.wikipedia.org/wiki/Calcium_carbide');
INSERT INTO inventions VALUES (258, 'Methyl methacrylate (Plexiglas)', 'Органическое стекло', 'Акриловая смола, синтетический виниловый полимер метилметакрилата, термопластичный прозрачный пластик, известный под наименованиями Plexiglas, Deglas, Acrylite, Lucite, Perspex, плексиглас, акрима, карбогласс, новаттро, плексима, лимакрил, плазкрил, акрилекс, акрилайт, акрипласт, акриловое стекло, акрил, метаплекс и многими другими. Может подвергаться окрашиванию и тонированию.', 1931, '{277}', 275, 'https://en.wikipedia.org/wiki/Poly(methyl_methacrylate)');
INSERT INTO inventions VALUES (259, 'Bin bag (garbage bag)', 'Мешок для мусора', 'Пластиковый мешок, предназначенный для размещения в нем мусора. Такие мешки обычно помещаются в различные контейнеры для мусора и не допускают загрязнения мусором внутренней поверхности этих контейнеров.', 1950, '{278}', 247, 'https://en.wikipedia.org/wiki/Bin_bag');
INSERT INTO inventions VALUES (260, 'Bi-pin connector', 'Двухштырьковый разъём', 'Стандартный двухконтактный разъём IEC для электроламп и светодиодов.', 1893, '{240}', 473, 'https://en.wikipedia.org/wiki/Bi-pin_connector');
INSERT INTO inventions VALUES (280, 'Tridilosa', 'Tridilosa', 'Очень легкая и прочная конструкция из стекла и бетона. Широко применяется в строительстве. ', 1966, '{296}', 286, 'https://en.wikipedia.org/wiki/Tridilosa');
INSERT INTO inventions VALUES (281, 'Synthesized Norethisterone', 'Норэтистерон', 'Синтетический женский половой гормон.', 1951, '{297}', 286, 'https://en.wikipedia.org/wiki/Norethisterone');
INSERT INTO inventions VALUES (261, 'Cardiac pacemaker ', 'Кардиостимулятор', 'Медицинский прибор, предназначенный для воздействия на ритм сердца. Основной задачей кардиостимулятора (водителя ритма) является поддержание или навязывание частоты сердечных сокращений пациенту, у которого сердце бьётся недостаточно часто, или имеется электрофизиологическое разобщение между предсердиями и желудочками (атриовентрикулярная блокада).', 1951, '{279}', 282, 'https://en.wikipedia.org/wiki/Cardiac_pacemaker');
INSERT INTO inventions VALUES (262, 'Alkaline battery', 'Щелочной элемент питания', 'Марганцево-цинковый гальванический элемент питания, в котором в качестве катода используется диоксид марганца, анода — порошкообразный цинк, а в качестве электролита — раствор щёлочи, обычно гидроксида калия.', 1954, '{280}', 475, 'https://en.wikipedia.org/wiki/Alkaline_battery');
INSERT INTO inventions VALUES (263, 'Caulking gun', 'Пистолет для уплотнения швов', NULL, 1894, '{281}', 0, 'https://en.wikipedia.org/wiki/Caulking');
INSERT INTO inventions VALUES (264, 'Electric oven', 'Элекстрическая плита', 'Кухонная плита, работающая на электричестве.', 1892, '{253}', 254, 'https://en.wikipedia.org/wiki/Electric_stove');
INSERT INTO inventions VALUES (265, 'Egg carton', 'Упаковка для яиц', 'Специальная коробка с ячейками для переноски куриных яиц', 1911, '{282}', 281, 'https://en.wikipedia.org/wiki/Egg_carton');
INSERT INTO inventions VALUES (266, 'Kerosene ', 'Керосин', 'Горючая смесь жидких углеводородов (от C8 до C15) с температурой кипения в интервале 150—250 °C, прозрачная, бесцветная (или слегка желтоватая), слегка маслянистая на ощупь, получаемая путём прямой перегонки или ректификации нефти.', 1846, '{283}', 456, 'https://en.wikipedia.org/wiki/Kerosene');
INSERT INTO inventions VALUES (267, 'Pulped wood paper', 'Процесс получения древесной массы', 'Волокнистый полуфабрикат для изготовления бумаги, который получают путём механического перетирания древесины в водной среде. При этом она расщепляется на микро- и макроскопические частицы разной формы. В состав древесной массы входят целлюлоза и лигнин. Это наиболее экономичный полуфабрикат с содержанием природного сырья. ', 1844, '{284}', 256, 'https://en.wikipedia.org/wiki/Pulp_(paper)');
INSERT INTO inventions VALUES (268, 'Paint roller', 'Малярный валик', 'Инструмент для нанесения лакокрасочных материалов (ЛКМ) и создания иных защитных и декоративных покрытий на различных поверхностях. Валик состоит из пластмассового ядра, представляющего собой тубус (трубку) из различных полимеров с бюгельным креплением подшипникового типа и шубки, которая крепится к ядру валика. ', 1940, '{285}', 282, 'https://en.wikipedia.org/wiki/Paint_roller');
INSERT INTO inventions VALUES (269, 'Robertson screw', 'Отверка Робертсона', 'Четырехгранная отвертка.', 1908, '{286}', 458, 'https://en.wikipedia.org/wiki/List_of_screw_drives#Robertson');
INSERT INTO inventions VALUES (270, 'Rotary vane pump', 'Пластинчатая гидромашина', 'Роторная объёмная гидромашина, вытеснителями в которой являются две и более пластин (шиберов).', 1874, '{287}', 476, 'https://en.wikipedia.org/wiki/Rotary_vane_pump');
INSERT INTO inventions VALUES (271, 'Guitarr?n mexicano', 'Гитаррон ("большая гитара")', 'Мексиканская шестиструнная бас-гитара очень крупных размеров, используемая в оркестрах мариачи. ', 0, '{0}', 0, 'https://en.wikipedia.org/wiki/Guitarr?n_mexicano');
INSERT INTO inventions VALUES (272, 'Mondrag?n rifle', 'Винтовка Мондрагона', 'Первая в мире самозарядная винтовка, разработанная в Мексике генералом Мануэлем Мондрагоном.', 1887, '{288}', 0, 'https://en.wikipedia.org/wiki/Mondrag?n_rifle');
INSERT INTO inventions VALUES (273, 'Sonido 13', 'Теория тринадцатого звука', 'Теория композитора Хулиана Каррильо, предполагающая то, что звукоряд может быть разделён на бесконечное число интервалов, насколько это возможно. В своей системе  выделяются трететоны, четвертитоны, шестинатоны и т.д. Помимо этого, композитор ввел цифровые обозначения двенадцати нот звукоряда в качестве образовательной методики обучения сольфеджио и композиции (0, начиная с до).', 1900, '{289}', 286, 'https://en.wikipedia.org/wiki/Sonido_13');
INSERT INTO inventions VALUES (274, 'Nachos', 'Начос', 'Закуска мексиканской кухни, представляющая собой чипсы из кукурузной тортильи с различными добавками', 1943, '{290}', 73, 'https://en.wikipedia.org/wiki/Nachos');
INSERT INTO inventions VALUES (275, 'Kahl?a', 'Калуа', 'Мексиканский кофейный ликёр.', 1936, '{0}', 0, 'https://en.wikipedia.org/wiki/Kahl?a');
INSERT INTO inventions VALUES (276, 'Japanese peanuts', 'Японский арахис', 'Легкая закуска из арахиса в твердом кляре.', 1940, '{291}', 0, 'https://en.wikipedia.org/wiki/Cracker_nuts');
INSERT INTO inventions VALUES (277, 'Color television', 'Цветное телевидение', 'Технология телевидения, позволяющая передавать движущееся изображение в натуральных цветах. ', 1934, '{292}', 286, 'https://en.wikipedia.org/wiki/Color_television');
INSERT INTO inventions VALUES (278, 'Electronic glove', 'Электронная перчатка', 'Устройство для преобразования жестов в звук или изображение текста на экране.', 2003, '{293}', 284, 'https://en.wikipedia.org/wiki/Jos?_Hern?ndez-Rebollar');
INSERT INTO inventions VALUES (279, 'GNOME', 'GNOME', 'Свободная среда рабочего стола для UNIX-подобных операционных систем. GNOME является частью проекта GNU.', 1999, '{267}', 294, 'https://en.wikipedia.org/wiki/GNOME');
INSERT INTO inventions VALUES (283, 'Metallic silhouette shooting', 'Силуэтная стрельба', 'Стрельба по мишеням, имеющим внешний вид, схожий с реальными объектами: людьми, животными и прочими.', 0, '{0}', 0, 'https://en.wikipedia.org/wiki/Metallic_silhouette_shooting');
INSERT INTO inventions VALUES (284, 'Election ink', 'Чернила для выборов', 'Чернила и красящее вещестово, наносимые на указательный палец избирателя с целю предотвращения фальсификации (двойное голосование). Это метод является эффективным в странах, где нет единого стандарта идентификационных документов.', 1994, '{299}', 286, 'https://en.wikipedia.org/wiki/Election_ink');
INSERT INTO inventions VALUES (285, 'Continuous-flow intersection', 'Перекресток с непрерывным движением', 'Альтернативная конструкция пресечения дорог, при которой автомобили, поворачивающие налево, совершают поворот до въезда на прекресток.', 1987, '{300,301}', 0, 'https://en.wikipedia.org/wiki/Continuous-flow_intersection');
INSERT INTO inventions VALUES (286, 'Franklin stove', 'Печь Франклина', 'Экономичная малогабаритная автономная печь для дома, созданная Бенджамином Франклином в 1742 году и принципиально усовершенствованная им же в 1770 году.', 1742, '{2}', 269, 'https://en.wikipedia.org/wiki/Franklin_stove');
INSERT INTO inventions VALUES (287, 'Mail order', 'Заказ товаров по почте', NULL, 1744, '{2}', 269, 'https://en.wikipedia.org/wiki/Mail_order');
INSERT INTO inventions VALUES (288, 'Lightning rod', 'Молниеотвод', 'Устройство, устанавливаемое на зданиях и сооружениях и служащее для защиты от удара молнии. В быту также употребляется некорректное, но более благозвучное «громоотвод».', 1749, '{2}', 269, 'https://en.wikipedia.org/wiki/Lightning_rod');
INSERT INTO inventions VALUES (289, 'Flexible urinary catheter', 'Гибкий мочевой катетер', 'Медицинское устройство, состоящее из длинной тонкой трубки и различных насадок. Устанавливается в уретру для вывода мочи.', 1752, '{2}', 269, 'https://en.wikipedia.org/wiki/Urinary_catheterization');
INSERT INTO inventions VALUES (290, 'Swivel chair', 'Вращающееся кресло', 'Кресло с одной центральной ножкой, способное поворачиваться на 360 градусов.', 1776, '{302}', 194, 'https://en.wikipedia.org/wiki/Swivel_chair');
INSERT INTO inventions VALUES (291, 'Diffraction grating', 'Дифракционная решётка', 'Оптический прибор, действие которого основано на использовании явления дифракции света. Представляет собой совокупность большого числа регулярно расположенных штрихов (щелей, выступов), нанесённых на некоторую поверхность', 1785, '{303}', 269, 'https://en.wikipedia.org/wiki/Diffraction_grating');
INSERT INTO inventions VALUES (292, 'Automatic flour mill', 'Автоматическая мукомольная мельница', 'Первая полностью автоматическая мельница.', 1787, '{5}', 287, 'https://en.wikipedia.org/wiki/Gristmill');
INSERT INTO inventions VALUES (293, 'Cotton gin', 'Коттон-джин', 'Первая эффективная хлопкоочистительная машина.Коттон-джин представляет собой деревянный ящик в котором вращаются два цилиндрических вала. На переднем насажены круглые пилы, а на заднем — щетки.', 1793, '{304}', 483, 'https://en.wikipedia.org/wiki/Cotton_gin');
INSERT INTO inventions VALUES (294, 'Wheel cypher', 'Цилиндр Джефферсона', 'Шифратор, придуманный Томасом Джефферсоном, состоящий из 36 дисков, на каждый из которых нанесен алфавит из 26 букв (не по порядку), диски надеты на одну ось и могут вращаться вокруг неё.', 1795, '{302}', 0, 'https://en.wikipedia.org/wiki/Jefferson_disk');
INSERT INTO inventions VALUES (295, 'Suspension bridge', 'Висячий мост', 'Мост, в котором основная несущая конструкция выполнена из гибких элементов (кабелей, канатов, цепей и других), работающих на растяжение, а проезжая часть подвешена.', 1801, '{305}', 484, 'https://en.wikipedia.org/wiki/Suspension_bridge');
INSERT INTO inventions VALUES (296, 'Amphibious vehicle', 'Машина-амфибия', 'Транспортное средство, способное передвигаться как по земле, так и по воде.', 1805, '{5}', 269, 'https://en.wikipedia.org/wiki/Amphibious_vehicle');
INSERT INTO inventions VALUES (297, 'Coffee percolator', 'Перколятор', 'Разновидность чайника (кофеварки) для приготовления кофе. Слово «перколятор» происходит от англ. percolation (в свою очередь от лат. percōlāre) — «просачивание». Перколятор обычно изготавливается из стали.', 1806, '{306}', 0, 'https://en.wikipedia.org/wiki/Coffee_percolator');
INSERT INTO inventions VALUES (298, 'Dental floss', 'Зубная нить', 'Специальная нитка для очистки межзубных промежутков.', 1815, '{307}', 265, 'https://en.wikipedia.org/wiki/Dental_floss');
INSERT INTO inventions VALUES (299, 'Milling machine', 'Фрезерование (фрезерный станок)', 'Процесс механической обработки, при котором режущий инструмент (фреза) совершает вращательное движение (со скоростью V), а обрабатываемая заготовка — поступательное (со скоростью подачи S).', 1816, '{308}', 487, 'https://en.wikipedia.org/wiki/Milling_(machining)');
INSERT INTO inventions VALUES (300, 'Profile lathe', 'Токарный станок', 'Станок для обработки резанием (точением) заготовок из металлов, древесины и других материалов в виде тел вращения. На токарных станках выполняют обточку и расточку цилиндрических, конических и фасонных поверхностей, нарезание резьбы, подрезку и обработку торцов, сверление, зенкерование и развёртывание отверстий и т. д. ', 1818, '{309}', 14, 'https://en.wikipedia.org/wiki/Lathe');
INSERT INTO inventions VALUES (301, 'Graham cracker', 'Крекер Грэма', 'Крекер из цельнозерновой муки.', 1829, '{310}', 0, 'https://en.wikipedia.org/wiki/Graham_cracker');
INSERT INTO inventions VALUES (302, 'Multiple coil magnet', 'Магнит с многокатушечной обмоткой', 'Электромагнит с параллельно соединенными обмотками, позволяющими увеличить подъемную силу.', 1831, '{7}', 156, 'https://en.wikipedia.org/wiki/Electromagnet');
INSERT INTO inventions VALUES (303, 'Sewing machine (lock-stitch)', 'Швейная машина', 'Техническое устройство для соединения и отделки материалов методом шитья. Швейные машины применяются в швейной, трикотажной, обувной и других отраслях лёгкой промышленности, а также в быту.', 1833, '{16}', 285, 'https://en.wikipedia.org/wiki/Sewing_machine');
INSERT INTO inventions VALUES (304, 'Steam shovel', 'Паровой экскаватор', 'Большая приведенная в действие паром производящая земляные работы машина, разработанная для подъема и перемещения материала, такого как скала и почва.', 1835, '{311}', 269, 'https://en.wikipedia.org/wiki/Steam_shovel');
INSERT INTO inventions VALUES (305, 'Solar compass', 'Солнечный компас', 'Прибор, при помощи которого направление меридиана определяется путем непрерывного слежения за солнцем с помощью специального устройства. ', 1835, '{22}', 270, 'https://en.wikipedia.org/wiki/Solar_compass');
INSERT INTO inventions VALUES (306, 'Circuit breaker', 'Автоматический выключатель', 'Контактный коммутационный аппарат, способный включать токи, проводить их и отключать при нормальных условиях в цепи, а также включать, проводить в течение нормированного времени и отключать токи при нормированных ненормальных условиях в цепи, таких как короткое замыкание.', 1836, '{312}', 284, 'https://en.wikipedia.org/wiki/Circuit_breaker');
INSERT INTO inventions VALUES (307, 'Sleeping car', 'Спальный вагон', 'Железнодорожный вагон, предназначенный для размещения пассажиров при их перевозке с обеспечением необходимых удобств в составе пассажирских поездов.', 1857, '{313}', 279, 'https://en.wikipedia.org/wiki/Sleeping_car');
INSERT INTO inventions VALUES (308, 'Vulcanization ', 'Вулканизация', 'Технологический процесс взаимодействия каучуков с вулканизирующим агентом, при котором происходит сшивание молекул каучука в единую пространственную сетку. При этом повышаются прочностные характеристики каучука, его твёрдость и эластичность, снижаются пластические свойства, степень набухания и растворимость в органических растворителях. ', 1839, '{314}', 269, 'https://en.wikipedia.org/wiki/Vulcanization');
INSERT INTO inventions VALUES (309, 'Babbitt', 'Баббит', 'Антифрикционный сплав на основе олова или свинца, предназначенный для использования в виде слоя, залитого или напыленного по корпусу вкладыша подшипника скольжения.', 1839, '{315}', 494, 'https://en.wikipedia.org/wiki/Babbitt_(alloy)');
INSERT INTO inventions VALUES (310, 'Grain elevator', 'Зерновой элеватор', 'Сооружение для хранения больших партий зерна и доведения его до кондиционного состояния. Элеватор представляет собой высокомеханизированное зернохранилище силосного типа.', 1842, '{316}', 236, 'https://en.wikipedia.org/wiki/Grain_elevator');
INSERT INTO inventions VALUES (311, 'Multiple-effect evaporator', 'Многокорпусный выпарной аппарат', NULL, 1843, '{317}', 265, 'https://en.wikipedia.org/wiki/Multiple-effect_evaporator');
INSERT INTO inventions VALUES (312, 'Maynard tape primer', 'Ленточный капсюль Мейнарда', 'Система быстрой перезарядки мушкета.', 1845, '{318}', 284, 'https://en.wikipedia.org/wiki/Maynard_tape_primer');
INSERT INTO inventions VALUES (313, 'Jackhammer', 'Отбойный молоток', 'Механический ручной инструмент ударного действия, предназначенный для разрыхления и раскалывания не очень крепких материалов, например: осадочных горных пород, асфальта, бетонных конструкций. Рабочим органом обычно является металлическое долото или пика. Механизация инструмента заключается в воздействии на исполнительный орган серии механических импульсов от бойка, который приводится в движение каким либо приводом.', 1849, '{319}', 269, 'https://en.wikipedia.org/wiki/Jackhammer');
INSERT INTO inventions VALUES (314, 'Burglar alarm', 'Охранная система', 'Автоматизированный комплекс для защиты различных объектов имущества (зданий, включая прилегающую к ним территорию, отдельных помещений, автомобилей, водного транспорта, сейфов и пр.) от процессов или явлений криминального характера. Термин является обобщающим для нескольких типов систем. Основное назначение — предупредить, по возможности предотвратить или способствовать предотвращению ситуаций, в которых будет нанесён вред людям или материальным и не материальным ценностям, связанных прежде всего с действиями других лиц.', 1853, '{320}', 495, 'https://en.wikipedia.org/wiki/Security_alarm');
INSERT INTO inventions VALUES (315, 'Dishwasher', 'Посудомоечная машина', 'Электромеханическая установка для автоматической мойки посуды. Применяется как в заведениях общественного питания, так и в домашних условиях. Посудомоечная машина подключается к электричеству, водопроводу и канализации.', 1886, '{321}', 498, 'https://en.wikipedia.org/wiki/Dishwasher');
INSERT INTO inventions VALUES (316, 'Screw top pepper shaker', 'Солонка с завинчивающейся крышкой', 'Небольшой сосуд для хранения соли, перца и иных приправ. В верхней части солонки имеются маленькие отверстия, через которые содержимое можно дозированно высыпать; в зависимости от размера и предназначения число таких отверстий у различных солонок может существенно отличаться. В учреждениях общественного питания солонки иногда подаются на уксуснице-подставке. Наполнение солонки происходит после снятия крышки.', 1858, '{322}', 269, 'https://en.wikipedia.org/wiki/Salt_and_pepper_shakers');
INSERT INTO inventions VALUES (317, 'Mason jar', 'Банка Мейсона', 'Стеклянная банка с завинчивающейся крышкой. Предназначена для консервирования продуктов питания.', 1858, '{322}', 269, 'https://en.wikipedia.org/wiki/Mason_jar');
INSERT INTO inventions VALUES (318, 'Breakfast cereal', 'Сухой зерновой завтрак ', 'Еда, приготовленная из сырых или запечённых злаков. Обычно смешивается с молоком или йогуртом.', 1863, '{323}', 501, 'https://en.wikipedia.org/wiki/Breakfast_cereal');
INSERT INTO inventions VALUES (319, 'Spar torpedo', 'Шестовая мина', 'Тип морского минного оружия, имевший применение в конце XIX века. Представлял собой заряд взрывчатого вещества, расположенного на конце длинного шеста.', 1864, '{324}', 0, 'https://en.wikipedia.org/wiki/Spar_torpedo');
INSERT INTO inventions VALUES (320, 'Water-tube boiler', 'Водотрубный котёл', 'Паровой или водогрейный котел, у которого поверхность нагрева (экран) состоит из кипятильных трубок, внутри которых движется теплоноситель. Теплообмен происходит посредством нагрева кипятильных трубок горячими продуктами сгорающего топлива. Различают прямоточные и барабанные водотрубные котлы. По конструкции является противоположностью газотрубному котлу (жаротрубному).', 1867, '{325,326}', 107, 'https://en.wikipedia.org/wiki/Water-tube_boiler');
INSERT INTO inventions VALUES (321, 'Tape measure', 'Рулетка', 'Инструмент для измерения длины. Представляет собой металлическую или пластмассовую ленту с нанесёнными делениями, которая намотана на катушку, заключённую в корпус, снабжённый механизмом для сматывания ленты.', 1868, '{327}', 55, 'https://en.wikipedia.org/wiki/Tape_measure');
INSERT INTO inventions VALUES (322, 'Clothes hanger', 'Вешалка', 'Приспособление для хранения одежды в подвешенном состоянии. ', 1869, '{328}', 504, 'https://en.wikipedia.org/wiki/Clothes_hanger');
INSERT INTO inventions VALUES (323, 'Sandblasting', 'Пескоструйная обработка', 'Холодная абразивная обработка поверхности камня, стекла, металлических изделий или зубов путём повреждения её поверхности песком или иным абразивным порошком, распыляемым потоком воздуха, а при гидроабразивной обработке — струёй воды или иной жидкости', 1870, '{329}', 269, 'https://en.wikipedia.org/wiki/Abrasive_blasting');
INSERT INTO inventions VALUES (324, 'Feather duster', 'Перьевая метёлка', 'Приспособление для очистки от пыли и грязи различных поверхностей, в том числе труднодоступных мест. Состоит, как правило, из деревянной ручки и прикрученного к ней с помощью проволоки пучка перьев какой-либо птицы, чаще всего страуса. Ныне большое распространение имеют метёлки с искусственными перьями, также существуют модели с выдвижными или съёмными ручками.', 1870, '{0}', 0, 'https://en.wikipedia.org/wiki/Feather_duster');
INSERT INTO inventions VALUES (325, 'Silo', 'Силос', 'Склад для хранения сыпучих материалов, таких как цемент, песок, зерно, комбикорм, гранулы и т. п. Силос представляет собой ёмкость цилиндрической формы с коническим днищем.', 1873, '{330}', 505, 'https://en.wikipedia.org/wiki/Silo');
INSERT INTO inventions VALUES (326, 'Fire sprinkler (automated)', 'Спринклерный ороситель', 'Составляющая системы пожаротушения, оросительная головка, вмонтированная в спринклерную установку (сеть водопроводных труб, в которых постоянно находится вода или воздух под давлением). ', 1874, '{331}', 55, 'https://en.wikipedia.org/wiki/Fire_sprinkler');
INSERT INTO inventions VALUES (327, 'Spork', 'Ложка-вилка', 'Столовый прибор, сочетающий элементы ложки и вилки. Употребляется главным образом для пищи быстрого приготовления. Изготавливается из металла, пластика либо дерева.', 1874, '{332}', 285, 'https://en.wikipedia.org/wiki/Spork');
INSERT INTO inventions VALUES (328, 'Forstner bit', 'Сверло Форстнера', 'Цилиндрическое сверло для проделывания несквозных отверстий с плоским дном в мягкой и твердой древесине.', 1874, '{333}', 175, 'https://en.wikipedia.org/wiki/Drill_bit#Forstner_bits');
INSERT INTO inventions VALUES (329, 'Mimeograph', 'Ротатор', 'Машина трафаретной печати, предназначенная для оперативного размножения книг малыми и средними тиражами. Трафареты изготовляют от руки или машинописным способом на восковой бумаге или плёнке, а также фотомеханическим, фотоэлектрическим или гальваническим способами.', 1875, '{45}', 67, 'https://en.wikipedia.org/wiki/Mimeograph');
INSERT INTO inventions VALUES (347, 'Muffler', 'Глушитель (акустический фильтр)', 'Устройство для снижения шума от выходящих в атмосферу газов или воздуха из различных устройств.', 1897, '{349}', 516, 'https://en.wikipedia.org/wiki/Muffler');
INSERT INTO inventions VALUES (330, 'Airbrush', 'Распылитель краски', 'Небольшой пневматический инструмент, пульверизатор, распыляющий краску или чернила. Аэрограф (аirbrush) — в переводе с английского означает «воздушная кисть») — приспособление для нанесения жидкого материала путём пневматического распыления. Внешне аэрограф очень напоминает авторучку, сверху, сбоку или снизу прикреплена небольшая ёмкость для эмалей, куда под давлением подается воздух.', 1876, '{334}', 325, 'https://en.wikipedia.org/wiki/Airbrush');
INSERT INTO inventions VALUES (331, 'Bolometer', 'Болометр', 'Тепловой приёмник излучения, чаще всего оптического (а именно — ИК-диапазона).', 1878, '{335}', 312, 'https://en.wikipedia.org/wiki/Bolometer');
INSERT INTO inventions VALUES (332, 'Carton', 'Картонная коробка', 'Упаковка из разных видов картона.', 1879, '{336}', 285, 'https://en.wikipedia.org/wiki/Carton');
INSERT INTO inventions VALUES (333, 'Thermostat', 'Термостат', 'Прибор для поддержания постоянной температуры. Поддержание температуры обеспечивается либо за счёт использования терморегуляторов, либо осуществлением фазового перехода (например, таяние льда). Для уменьшения потерь тепла или холода термостаты, как правило, теплоизолируют. Но не всегда. Широко известны автомобильные моторы, где летом нет никакой теплоизоляции и за счёт действия восковых термостатов поддерживается постоянная температура. Другим примером термостата является холодильник.', 1883, '{337}', 511, 'https://en.wikipedia.org/wiki/Thermostat');
INSERT INTO inventions VALUES (334, 'Fuel dispenser', 'Топливораздаточная колонка', 'Аппарат для раздачи различных видов топлива и масла. Устанавливается на автозаправках.', 1885, '{338}', 63, 'https://en.wikipedia.org/wiki/Fuel_dispenser');
INSERT INTO inventions VALUES (335, 'Telephone directory', 'Телефонный справочник', 'Список абонентов телефонной сети.', 1886, '{339}', 279, 'https://en.wikipedia.org/wiki/Telephone_directory');
INSERT INTO inventions VALUES (336, 'Comptometer', 'Комптометр', 'Первый коммерчески успешный кнопочный механический калькулятор.', 1887, '{340}', 279, 'https://en.wikipedia.org/wiki/Comptometer');
INSERT INTO inventions VALUES (337, 'Induction motor', 'Асинхронная (индукционная) машина', 'Электрическая машина переменного тока, частота вращения ротора которой не равна (в двигательном режиме меньше) частоте вращения магнитного поля, создаваемого током обмотки статора.', 1888, '{66}', 285, 'https://en.wikipedia.org/wiki/Induction_motor');
INSERT INTO inventions VALUES (338, 'Ballpoint pen', 'Шариковая ручка', 'Разновидность ручки (авторучки), при письме которой чернила переносятся из резервуара на бумагу вращающимся шариком. Состоит из стержня — пластиковой трубочки, заполненной пастообразными чернилами, и шарикового пишущего узла (наконечника), размещённого на конце стержня.', 1888, '{341}', 513, 'https://en.wikipedia.org/wiki/Ballpoint_pen');
INSERT INTO inventions VALUES (339, 'Telautograph', 'Фототелеграф', 'Ранняя технология факсимильной связи, разработанная для передачи полутоновых изображений на расстояние. ', 1888, '{44}', 514, 'https://en.wikipedia.org/wiki/Telautograph');
INSERT INTO inventions VALUES (340, 'Payphone', 'Таксофон', 'Телефонный аппарат общего пользования. Оплата может производиться при помощи монет, жетонов или телефонных, дебетовых либо кредитных карт.', 1889, '{342}', 106, 'https://en.wikipedia.org/wiki/Payphone');
INSERT INTO inventions VALUES (341, 'Tabulating machine', 'Табулятор', 'Электромеханическая машина, предназначенная для автоматической обработки (суммирования и категоризации) числовой и буквенной информации, записанной на перфокартах, с выдачей результатов на бумажную ленту или специальные бланки.', 1890, '{343}', 284, 'https://en.wikipedia.org/wiki/Tabulating_machine');
INSERT INTO inventions VALUES (342, 'Schrader valve', 'Клапан Шрадера', 'Тип клапана для камер, используемый сегодня в шинах почти всех транспортных средств в мире. Клапан Шрадера состоит из трубки, в которую вкручивается сердцевина (золотник), и используется почти на всех автомобильных, мотоциклетных, а также многих велосипедных шинах. Рабочий элемент представляет собой тарельчатый клапан со вспомогательной пружиной.', 1891, '{344}', 285, 'https://en.wikipedia.org/wiki/Schrader_valve');
INSERT INTO inventions VALUES (343, 'Dimmer', 'Диммер', 'Электронное устройство, предназначенное для изменения электрической мощности (регулятор мощности). Обычно используется для регулировки яркости света, излучаемого лампами накаливания или светодиодами.', 1892, '{345}', 285, 'https://en.wikipedia.org/wiki/Dimmer');
INSERT INTO inventions VALUES (344, 'Spectroheliograph', 'Спектрогелиограф ', 'Спектральный астрономический прибор для фотографирования солнечного диска в монохроматическом свете.', 1893, '{346}', 316, 'https://en.wikipedia.org/wiki/Spectroheliograph');
INSERT INTO inventions VALUES (345, 'Phantoscope', 'Фантоскоп', 'Один из первых кинопроекторов.', 1894, '{347}', 284, 'https://en.wikipedia.org/wiki/Phantoscope');
INSERT INTO inventions VALUES (346, 'Stadimeter', 'Штурманский дальномер', 'Оптическое устройство, предназначенное для определения расстояния от наблюдателя до объекта.', 1894, '{348}', 285, 'https://en.wikipedia.org/wiki/Stadimeter');
INSERT INTO inventions VALUES (348, 'Sousaphone', 'Сузафон', 'Медный духовой инструмент басового звучания, разновидность геликона (отличается главным образом увеличенным размером).', 1898, '{350}', 518, 'https://en.wikipedia.org/wiki/Sousaphone');
INSERT INTO inventions VALUES (349, 'Flash-lamp', 'Фотовспышка', 'Магниевая вспышка с электрическим запалом.', 1899, '{351}', 285, 'https://en.wikipedia.org/wiki/Flash-lamp');


--
-- TOC entry 2198 (class 0 OID 0)
-- Dependencies: 197
-- Name: inventions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('inventions_id_seq', 350, false);


--
-- TOC entry 2073 (class 2606 OID 16827)
-- Name: inventions inventions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventions
    ADD CONSTRAINT inventions_pkey PRIMARY KEY (id);


-- Completed on 2017-09-08 11:20:08 UTC

--
-- PostgreSQL database dump complete
--

