name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: |
          npm run lint
          npm run stylelint
      - name: Build Release
        run: npm run release
      - name: Save Release
        uses: actions/cache@v2
        id: release-data
        with:
          path: ./dist
          key: ${{ github.sha }}
  image:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      MESSAGE: ${{ github.event.head_commit.message }}
      OLDEST: ${{ github.event.commits[0].message }}
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: Print Branch Name
        run: echo ${{ env.BRANCH_NAME }}
      - run: |
          echo Message ${MESSAGE}
          echo OLDEST ${OLDEST}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        id: release-data
        with:
          path: ./dist
          key: ${{ github.sha }}
      - run: cp -R dist dist_release
      - name: "Build Docker Image"
        run: docker build -t "chronmaps/frontend:latest" . -f Dockerfile.prebuild
      # - name: "Publish Docker Image"
        # run: docker push "chronmaps/frontend:${TAG}"
