name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: |
          npm run lint
          npm run stylelint
      - name: Build Release
        run: npm run release
      - name: Save Release
        uses: actions/cache@v2
        id: release-data
        with:
          path: |
            ./static
            ./dist
          key: ${{ github.sha }}
  image:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/cache@v2
        id: release-data
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: ls -la